-- ============================================================
-- Módulo de venta de productos (separado de boletas)
-- Ejecutar en Supabase SQL Editor
-- ============================================================

-- Catálogo por evento
CREATE TABLE IF NOT EXISTS public.productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id BIGINT NOT NULL REFERENCES public.eventos(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  precio NUMERIC(12, 2) NOT NULL CHECK (precio >= 0),
  imagen_url TEXT,
  es_licor BOOLEAN NOT NULL DEFAULT false,
  cantidad_total INT NOT NULL DEFAULT 0 CHECK (cantidad_total >= 0),
  cantidad_vendidas INT NOT NULL DEFAULT 0 CHECK (cantidad_vendidas >= 0),
  cantidad_disponibles INT GENERATED ALWAYS AS (GREATEST(0, cantidad_total - cantidad_vendidas)) STORED,
  limite_por_persona INT CHECK (limite_por_persona IS NULL OR limite_por_persona > 0),
  fecha_venta_inicio TIMESTAMPTZ,
  fecha_venta_fin TIMESTAMPTZ,
  activo BOOLEAN NOT NULL DEFAULT true,
  orden INT NOT NULL DEFAULT 0,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_productos_evento ON public.productos(evento_id, activo);

-- Cabecera de compra de productos (independiente de compras de boletas)
CREATE TABLE IF NOT EXISTS public.compras_productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL REFERENCES public.usuarios(id),
  evento_id BIGINT NOT NULL REFERENCES public.eventos(id),
  wompi_cuenta_id BIGINT REFERENCES public.wompi_cuentas(id),
  numero_pedido TEXT NOT NULL UNIQUE,
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
  porcentaje_servicio NUMERIC(5, 2) NOT NULL DEFAULT 0,
  valor_servicio NUMERIC(12, 2) NOT NULL DEFAULT 0,
  descuento_total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  estado_pago public.tipo_estado_pago NOT NULL DEFAULT 'pendiente',
  estado_compra public.tipo_estado_compra NOT NULL DEFAULT 'pendiente',
  terminos_licor_aceptados BOOLEAN NOT NULL DEFAULT false,
  terminos_licor_aceptados_at TIMESTAMPTZ,
  datos_facturacion JSONB,
  fecha_compra TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_confirmacion TIMESTAMPTZ,
  fecha_cancelacion TIMESTAMPTZ,
  motivo_cancelacion TEXT
);

CREATE INDEX IF NOT EXISTS idx_compras_productos_cliente ON public.compras_productos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_compras_productos_evento ON public.compras_productos(evento_id);

-- Líneas de la compra
CREATE TABLE IF NOT EXISTS public.compras_productos_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_producto_id BIGINT NOT NULL REFERENCES public.compras_productos(id) ON DELETE CASCADE,
  producto_id BIGINT NOT NULL REFERENCES public.productos(id),
  cantidad INT NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(12, 2) NOT NULL CHECK (precio_unitario >= 0),
  subtotal_linea NUMERIC(12, 2) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
  estado TEXT NOT NULL DEFAULT 'pendiente',
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_compras_productos_items_compra ON public.compras_productos_items(compra_producto_id);

-- Transacción Wompi (id enviado / payment_link_id)
CREATE TABLE IF NOT EXISTS public.transacciones_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_producto_id BIGINT NOT NULL REFERENCES public.compras_productos(id) ON DELETE CASCADE,
  wompi_cuenta_id BIGINT REFERENCES public.wompi_cuentas(id),
  numero_transaccion TEXT NOT NULL,
  wompi_transaction_id TEXT,
  wompi_reference TEXT,
  wompi_status TEXT,
  monto NUMERIC(12, 2) NOT NULL,
  monto_centavos INT NOT NULL,
  moneda TEXT NOT NULL DEFAULT 'COP',
  estado TEXT NOT NULL DEFAULT 'pendiente',
  checkout_url TEXT,
  redirect_url TEXT,
  request_payload JSONB,
  response_payload JSONB,
  webhook_payload JSONB,
  es_activa BOOLEAN NOT NULL DEFAULT true,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_confirmacion TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_transacciones_producto_compra ON public.transacciones_producto(compra_producto_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_transacciones_producto_wompi_tx
  ON public.transacciones_producto(wompi_transaction_id)
  WHERE wompi_transaction_id IS NOT NULL;

-- Confirmar pago: incrementar vendidos
CREATE OR REPLACE FUNCTION public.confirmar_compra_producto(p_compra_producto_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  r RECORD;
BEGIN
  UPDATE public.compras_productos
  SET estado_pago = 'completado',
      estado_compra = 'confirmada',
      fecha_confirmacion = now()
  WHERE id = p_compra_producto_id
    AND estado_pago IS DISTINCT FROM 'completado';

  FOR r IN
    SELECT i.producto_id, i.cantidad
    FROM public.compras_productos_items i
    WHERE i.compra_producto_id = p_compra_producto_id
  LOOP
    UPDATE public.productos
    SET cantidad_vendidas = cantidad_vendidas + r.cantidad,
        fecha_actualizacion = now()
    WHERE id = r.producto_id;

    UPDATE public.compras_productos_items
    SET estado = 'confirmado'
    WHERE compra_producto_id = p_compra_producto_id
      AND producto_id = r.producto_id;
  END LOOP;
END;
$$;

COMMENT ON TABLE public.productos IS 'Catálogo de productos por evento (venta separada de boletas)';
COMMENT ON TABLE public.compras_productos IS 'Pedidos de productos';
COMMENT ON TABLE public.transacciones_producto IS 'Intentos de pago Wompi para compras de productos';
