-- ============================================================
-- 003_transacciones_checkout_unificada.sql
-- Capa unificada de intento de pago (boletas / productos / mixto)
-- NO reemplaza compras ni compras_productos; solo agrega orquestacion
-- ============================================================

-- 1) Tabla principal de intentos de checkout
CREATE TABLE IF NOT EXISTS public.transacciones_checkout (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Tipo de intento
  tipo TEXT NOT NULL CHECK (tipo IN ('boletas', 'productos', 'mixto')),

  -- Relacion de contexto
  cliente_id BIGINT NOT NULL REFERENCES public.usuarios(id),
  evento_id BIGINT NOT NULL REFERENCES public.eventos(id),
  wompi_cuenta_id BIGINT REFERENCES public.wompi_cuentas(id),

  -- Relacion con resultados finales (se llenan al materializar APPROVED)
  compra_id BIGINT REFERENCES public.compras(id) ON DELETE SET NULL,
  compra_producto_id BIGINT REFERENCES public.compras_productos(id) ON DELETE SET NULL,

  -- Identificadores internos/externos
  numero_intento TEXT NOT NULL UNIQUE,
  wompi_transaction_id TEXT,
  wompi_reference TEXT,
  wompi_status TEXT,

  -- Monto snapshot
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  descuento_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  porcentaje_servicio NUMERIC(5,2) NOT NULL DEFAULT 0,
  valor_servicio NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  monto_centavos INT NOT NULL DEFAULT 0,
  moneda TEXT NOT NULL DEFAULT 'COP',

  -- Estado del intento
  estado TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente','aprobada','rechazada','cancelada','expirada','error')),
  es_activa BOOLEAN NOT NULL DEFAULT true,

  -- Trazabilidad / payloads
  checkout_url TEXT,
  redirect_url TEXT,
  request_payload JSONB,
  response_payload JSONB,
  webhook_payload JSONB,
  metadata JSONB,

  -- Control de materializacion e idempotencia
  materializado BOOLEAN NOT NULL DEFAULT false,
  materializado_at TIMESTAMPTZ,
  flow_version TEXT NOT NULL DEFAULT 'v1-unificado',

  -- Expiracion
  expires_at TIMESTAMPTZ,

  -- Auditoria
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_confirmacion TIMESTAMPTZ,
  fecha_cancelacion TIMESTAMPTZ,
  motivo_cancelacion TEXT
);

COMMENT ON TABLE public.transacciones_checkout IS
  'Intento unificado de pago para boletas/productos/mixto. Materializa compras finales al APPROVED.';

COMMENT ON COLUMN public.transacciones_checkout.request_payload IS
  'Snapshot completo del carrito y contexto del checkout al momento de crear el link.';

COMMENT ON COLUMN public.transacciones_checkout.materializado IS
  'Evita doble creacion por webhooks repetidos.';

-- 2) Indices recomendados
CREATE INDEX IF NOT EXISTS idx_tx_checkout_cliente
  ON public.transacciones_checkout(cliente_id, fecha_creacion DESC);

CREATE INDEX IF NOT EXISTS idx_tx_checkout_evento
  ON public.transacciones_checkout(evento_id, fecha_creacion DESC);

CREATE INDEX IF NOT EXISTS idx_tx_checkout_estado_activa
  ON public.transacciones_checkout(estado, es_activa, fecha_creacion);

CREATE INDEX IF NOT EXISTS idx_tx_checkout_wompi_ref
  ON public.transacciones_checkout(wompi_reference)
  WHERE wompi_reference IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tx_checkout_wompi_tx
  ON public.transacciones_checkout(wompi_transaction_id)
  WHERE wompi_transaction_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tx_checkout_compra
  ON public.transacciones_checkout(compra_id)
  WHERE compra_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tx_checkout_compra_producto
  ON public.transacciones_checkout(compra_producto_id)
  WHERE compra_producto_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tx_checkout_expires
  ON public.transacciones_checkout(expires_at)
  WHERE expires_at IS NOT NULL;

-- 3) Trigger para fecha_actualizacion
CREATE OR REPLACE FUNCTION public.set_tx_checkout_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.fecha_actualizacion := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_tx_checkout_updated_at ON public.transacciones_checkout;

CREATE TRIGGER trg_set_tx_checkout_updated_at
BEFORE UPDATE ON public.transacciones_checkout
FOR EACH ROW
EXECUTE FUNCTION public.set_tx_checkout_updated_at();

-- 4) RLS (si ya usas RLS, service role de edge functions mantiene acceso)
ALTER TABLE public.transacciones_checkout ENABLE ROW LEVEL SECURITY;

-- Politica de lectura para dueno (cliente)
DROP POLICY IF EXISTS tx_checkout_select_own ON public.transacciones_checkout;
CREATE POLICY tx_checkout_select_own
ON public.transacciones_checkout
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.usuarios u
    WHERE u.id = transacciones_checkout.cliente_id
      AND u.auth_user_id = auth.uid()
  )
);

-- Politica explicita para service role
DROP POLICY IF EXISTS tx_checkout_all_service_role ON public.transacciones_checkout;
CREATE POLICY tx_checkout_all_service_role
ON public.transacciones_checkout
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- 5) Vista opcional para depuracion operativa
CREATE OR REPLACE VIEW public.vw_tx_checkout_resumen AS
SELECT
  id,
  tipo,
  cliente_id,
  evento_id,
  estado,
  es_activa,
  materializado,
  wompi_status,
  total,
  moneda,
  numero_intento,
  wompi_reference,
  wompi_transaction_id,
  expires_at,
  fecha_creacion,
  fecha_actualizacion,
  fecha_confirmacion,
  fecha_cancelacion
FROM public.transacciones_checkout;
