-- ============================================================
-- Permisos de lectores para redencion de productos por evento
-- ============================================================

CREATE TABLE IF NOT EXISTS public.lector_evento_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  evento_id BIGINT NOT NULL REFERENCES public.eventos(id) ON DELETE CASCADE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT lector_evento_producto_unique UNIQUE (usuario_id, evento_id)
);

CREATE INDEX IF NOT EXISTS idx_lector_evento_producto_usuario
  ON public.lector_evento_producto(usuario_id);

CREATE INDEX IF NOT EXISTS idx_lector_evento_producto_evento
  ON public.lector_evento_producto(evento_id);

ALTER TABLE public.lector_evento_producto ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS lep_select_self_admin_organizador ON public.lector_evento_producto;
CREATE POLICY lep_select_self_admin_organizador
ON public.lector_evento_producto
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.usuarios actor
    WHERE actor.auth_user_id = auth.uid()
      AND (
        actor.id = lector_evento_producto.usuario_id
        OR actor.tipo_usuario_id = 3
        OR (
          actor.tipo_usuario_id = 2
          AND EXISTS (
            SELECT 1
            FROM public.eventos ev
            WHERE ev.id = lector_evento_producto.evento_id
              AND ev.organizador_id = actor.id
          )
        )
      )
  )
);

DROP POLICY IF EXISTS lep_insert_admin_organizador ON public.lector_evento_producto;
CREATE POLICY lep_insert_admin_organizador
ON public.lector_evento_producto
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.usuarios actor
    WHERE actor.auth_user_id = auth.uid()
      AND (
        actor.tipo_usuario_id = 3
        OR (
          actor.tipo_usuario_id = 2
          AND EXISTS (
            SELECT 1
            FROM public.eventos ev
            WHERE ev.id = lector_evento_producto.evento_id
              AND ev.organizador_id = actor.id
          )
        )
      )
  )
);

DROP POLICY IF EXISTS lep_delete_admin_organizador ON public.lector_evento_producto;
CREATE POLICY lep_delete_admin_organizador
ON public.lector_evento_producto
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.usuarios actor
    WHERE actor.auth_user_id = auth.uid()
      AND (
        actor.tipo_usuario_id = 3
        OR (
          actor.tipo_usuario_id = 2
          AND EXISTS (
            SELECT 1
            FROM public.eventos ev
            WHERE ev.id = lector_evento_producto.evento_id
              AND ev.organizador_id = actor.id
          )
        )
      )
  )
);

DROP POLICY IF EXISTS lep_service_role_all ON public.lector_evento_producto;
CREATE POLICY lep_service_role_all
ON public.lector_evento_producto
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
