-- Notificaciones en tiempo real para cliente (mis-compras)
-- Caso principal: cuando una boleta pasa a "usada" en escaneo.

CREATE TABLE IF NOT EXISTS public.notificaciones_usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  titulo TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  metadata JSONB,
  leida BOOLEAN NOT NULL DEFAULT false,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_lectura TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario_usuario_fecha
  ON public.notificaciones_usuario(usuario_id, fecha_creacion DESC);

CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario_no_leidas
  ON public.notificaciones_usuario(usuario_id, leida)
  WHERE leida = false;

ALTER TABLE public.notificaciones_usuario ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS notificaciones_select_own ON public.notificaciones_usuario;
CREATE POLICY notificaciones_select_own
ON public.notificaciones_usuario
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.usuarios u
    WHERE u.id = notificaciones_usuario.usuario_id
      AND u.auth_user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS notificaciones_update_own ON public.notificaciones_usuario;
CREATE POLICY notificaciones_update_own
ON public.notificaciones_usuario
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.usuarios u
    WHERE u.id = notificaciones_usuario.usuario_id
      AND u.auth_user_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.usuarios u
    WHERE u.id = notificaciones_usuario.usuario_id
      AND u.auth_user_id = auth.uid()
  )
);

GRANT SELECT, UPDATE ON public.notificaciones_usuario TO authenticated;
GRANT SELECT, UPDATE ON public.notificaciones_usuario TO service_role;

-- Realtime: asegurar que la tabla esté publicada.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'notificaciones_usuario'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.notificaciones_usuario;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.fn_notificar_entrada_validada()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_usuario_objetivo BIGINT;
  v_evento_id BIGINT;
  v_evento_titulo TEXT;
BEGIN
  IF NEW.estado IS DISTINCT FROM OLD.estado AND NEW.estado = 'usada' THEN
    SELECT c.cliente_id, c.evento_id
      INTO v_usuario_objetivo, v_evento_id
    FROM public.compras c
    WHERE c.id = NEW.compra_id;

    IF NEW.titular_cliente_id IS NOT NULL THEN
      v_usuario_objetivo := NEW.titular_cliente_id;
    END IF;

    SELECT e.titulo
      INTO v_evento_titulo
    FROM public.eventos e
    WHERE e.id = v_evento_id;

    IF v_usuario_objetivo IS NOT NULL THEN
      INSERT INTO public.notificaciones_usuario (
        usuario_id,
        tipo,
        titulo,
        mensaje,
        metadata
      )
      VALUES (
        v_usuario_objetivo,
        'entrada_validada',
        'Entrada validada',
        COALESCE(
          'Tu entrada del evento "' || COALESCE(v_evento_titulo, 'Evento') || '" fue validada en puerta.',
          'Tu entrada fue validada en puerta.'
        ),
        jsonb_build_object(
          'boleta_id', NEW.id,
          'compra_id', NEW.compra_id,
          'evento_id', v_evento_id,
          'codigo_qr', NEW.codigo_qr,
          'estado', NEW.estado,
          'fecha_uso', NEW.fecha_uso
        )
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notificar_entrada_validada ON public.boletas_compradas;
CREATE TRIGGER trg_notificar_entrada_validada
AFTER UPDATE ON public.boletas_compradas
FOR EACH ROW
EXECUTE FUNCTION public.fn_notificar_entrada_validada();

CREATE OR REPLACE FUNCTION public.fn_notificar_productos_redimidos()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_usuario_objetivo BIGINT;
  v_evento_id BIGINT;
  v_evento_titulo TEXT;
  v_numero_pedido TEXT;
  v_total_pendientes BIGINT;
BEGIN
  IF NEW.estado IS DISTINCT FROM OLD.estado AND NEW.estado = 'entregado' THEN
    SELECT cp.cliente_id, cp.evento_id, cp.numero_pedido
      INTO v_usuario_objetivo, v_evento_id, v_numero_pedido
    FROM public.compras_productos cp
    WHERE cp.id = NEW.compra_producto_id;

    -- Solo avisar cuando TODO el pedido quedó redimido
    SELECT COUNT(*)
      INTO v_total_pendientes
    FROM public.compras_productos_items i
    WHERE i.compra_producto_id = NEW.compra_producto_id
      AND COALESCE(i.estado, 'pendiente') <> 'entregado';

    IF v_total_pendientes = 0 AND v_usuario_objetivo IS NOT NULL THEN
      SELECT e.titulo
        INTO v_evento_titulo
      FROM public.eventos e
      WHERE e.id = v_evento_id;

      INSERT INTO public.notificaciones_usuario (
        usuario_id,
        tipo,
        titulo,
        mensaje,
        metadata
      )
      VALUES (
        v_usuario_objetivo,
        'productos_redimidos',
        'Productos redimidos',
        COALESCE(
          'Tu pedido ' || COALESCE(v_numero_pedido, ('#' || NEW.compra_producto_id::TEXT)) ||
          ' del evento "' || COALESCE(v_evento_titulo, 'Evento') || '" fue redimido.',
          'Tu pedido de productos fue redimido.'
        ),
        jsonb_build_object(
          'compra_producto_id', NEW.compra_producto_id,
          'evento_id', v_evento_id,
          'numero_pedido', v_numero_pedido,
          'estado', NEW.estado,
          'fecha_redencion', NEW.fecha_redencion
        )
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notificar_productos_redimidos ON public.compras_productos_items;
CREATE TRIGGER trg_notificar_productos_redimidos
AFTER UPDATE ON public.compras_productos_items
FOR EACH ROW
EXECUTE FUNCTION public.fn_notificar_productos_redimidos();
