-- Módulo Cupos Eventum (único script, idempotente)
-- Incluye: tablón por evento + vista global "Mis cupos"
-- Seguro si ya ejecutaste una versión anterior del 011 y/o el 012 por separado.

-- ─── Tablas ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.avisos_cupo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id BIGINT NOT NULL REFERENCES public.eventos(id) ON DELETE CASCADE,
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL CHECK (tipo IN ('busco_cupo', 'ofrezco_cupo', 'busco_grupo')),
  descripcion TEXT NOT NULL CHECK (char_length(trim(descripcion)) >= 10),
  cupos INTEGER NOT NULL DEFAULT 1 CHECK (cupos >= 1 AND cupos <= 50),
  zona_texto TEXT,
  precio_referencia_cop BIGINT CHECK (precio_referencia_cop IS NULL OR precio_referencia_cop >= 0),
  boleta_id BIGINT REFERENCES public.boletas_compradas(id) ON DELETE SET NULL,
  estado TEXT NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'cerrado', 'oculto')),
  autor_display TEXT NOT NULL,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_cierre TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_avisos_cupo_evento_activo
  ON public.avisos_cupo(evento_id, fecha_creacion DESC)
  WHERE estado = 'activo';

CREATE INDEX IF NOT EXISTS idx_avisos_cupo_usuario
  ON public.avisos_cupo(usuario_id, fecha_creacion DESC);

CREATE INDEX IF NOT EXISTS idx_avisos_cupo_usuario_activo
  ON public.avisos_cupo(usuario_id, fecha_creacion DESC)
  WHERE estado = 'activo';

CREATE TABLE IF NOT EXISTS public.intereses_cupo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aviso_id BIGINT NOT NULL REFERENCES public.avisos_cupo(id) ON DELETE CASCADE,
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  mensaje TEXT NOT NULL CHECK (char_length(trim(mensaje)) >= 5),
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'visto', 'cerrado')),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (aviso_id, usuario_id)
);

CREATE INDEX IF NOT EXISTS idx_intereses_cupo_aviso
  ON public.intereses_cupo(aviso_id, fecha_creacion DESC);

CREATE TABLE IF NOT EXISTS public.reportes_cupo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aviso_id BIGINT NOT NULL REFERENCES public.avisos_cupo(id) ON DELETE CASCADE,
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  motivo TEXT,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (aviso_id, usuario_id)
);

-- ─── RLS ────────────────────────────────────────────────────────────────────

ALTER TABLE public.avisos_cupo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intereses_cupo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reportes_cupo ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS avisos_cupo_select_authenticated ON public.avisos_cupo;
CREATE POLICY avisos_cupo_select_authenticated ON public.avisos_cupo
  FOR SELECT TO authenticated
  USING (
    estado = 'activo'
    OR usuario_id IN (
      SELECT u.id FROM public.usuarios u WHERE u.auth_user_id = auth.uid()
    )
  );

GRANT SELECT ON public.avisos_cupo TO authenticated;
GRANT SELECT ON public.intereses_cupo TO authenticated;
GRANT SELECT ON public.reportes_cupo TO authenticated;

-- ─── Helpers (CREATE OR REPLACE = re-ejecutable) ────────────────────────────

CREATE OR REPLACE FUNCTION public.fn_usuario_id_actual()
RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT u.id FROM public.usuarios u WHERE u.auth_user_id = auth.uid() LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.fn_autor_display(p_usuario_id BIGINT)
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT trim(
    coalesce(nullif(trim(u.nombre), ''), 'Usuario')
    || coalesce(' ' || left(nullif(trim(u.apellido), ''), 1), '')
  )
  FROM public.usuarios u
  WHERE u.id = p_usuario_id;
$$;

-- ─── RPC: tablón por evento ─────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.listar_avisos_cupo_evento(
  p_evento_id BIGINT,
  p_tipo TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result JSONB;
BEGIN
  IF p_evento_id IS NULL OR p_evento_id <= 0 THEN
    RETURN '[]'::jsonb;
  END IF;

  SELECT coalesce(jsonb_agg(row_to_json(t)::jsonb ORDER BY t.fecha_creacion DESC), '[]'::jsonb)
  INTO v_result
  FROM (
    SELECT
      a.id,
      a.evento_id,
      a.tipo,
      a.descripcion,
      a.cupos,
      a.zona_texto,
      a.precio_referencia_cop,
      a.autor_display,
      a.fecha_creacion,
      (SELECT count(*)::int FROM public.intereses_cupo i WHERE i.aviso_id = a.id AND i.estado <> 'cerrado') AS intereses_count,
      (public.fn_usuario_id_actual() IS NOT NULL AND a.usuario_id = public.fn_usuario_id_actual()) AS es_mio
    FROM public.avisos_cupo a
    WHERE a.evento_id = p_evento_id
      AND a.estado = 'activo'
      AND (p_tipo IS NULL OR a.tipo = p_tipo)
  ) t;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.crear_aviso_cupo(
  p_evento_id BIGINT,
  p_tipo TEXT,
  p_descripcion TEXT,
  p_cupos INTEGER DEFAULT 1,
  p_zona_texto TEXT DEFAULT NULL,
  p_precio_referencia_cop BIGINT DEFAULT NULL,
  p_boleta_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_aviso public.avisos_cupo%ROWTYPE;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Debes iniciar sesión');
  END IF;

  IF p_tipo NOT IN ('busco_cupo', 'ofrezco_cupo', 'busco_grupo') THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Tipo de aviso no válido');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.eventos e WHERE e.id = p_evento_id AND e.activo = true) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Evento no disponible');
  END IF;

  IF p_tipo = 'ofrezco_cupo' AND p_boleta_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.boletas_compradas b
      JOIN public.compras c ON c.id = b.compra_id
      WHERE b.id = p_boleta_id
        AND c.cliente_id = v_uid
        AND c.evento_id = p_evento_id
        AND b.estado = 'pendiente'
    ) THEN
      RETURN jsonb_build_object('ok', false, 'error', 'La boleta no es válida para este evento');
    END IF;
  END IF;

  INSERT INTO public.avisos_cupo (
    evento_id, usuario_id, tipo, descripcion, cupos, zona_texto,
    precio_referencia_cop, boleta_id, autor_display
  ) VALUES (
    p_evento_id, v_uid, p_tipo, trim(p_descripcion), coalesce(p_cupos, 1),
    nullif(trim(p_zona_texto), ''),
    p_precio_referencia_cop, p_boleta_id,
    public.fn_autor_display(v_uid)
  )
  RETURNING * INTO v_aviso;

  RETURN jsonb_build_object('ok', true, 'aviso_id', v_aviso.id);
END;
$$;

CREATE OR REPLACE FUNCTION public.registrar_interes_cupo(
  p_aviso_id BIGINT,
  p_mensaje TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_aviso public.avisos_cupo%ROWTYPE;
  v_interes_id BIGINT;
  v_display TEXT;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Debes iniciar sesión');
  END IF;

  SELECT * INTO v_aviso FROM public.avisos_cupo WHERE id = p_aviso_id AND estado = 'activo';
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Aviso no disponible');
  END IF;

  IF v_aviso.usuario_id = v_uid THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No puedes mostrar interés en tu propio aviso');
  END IF;

  INSERT INTO public.intereses_cupo (aviso_id, usuario_id, mensaje)
  VALUES (p_aviso_id, v_uid, trim(p_mensaje))
  ON CONFLICT (aviso_id, usuario_id) DO UPDATE
    SET mensaje = EXCLUDED.mensaje, estado = 'pendiente', fecha_creacion = now()
  RETURNING id INTO v_interes_id;

  v_display := public.fn_autor_display(v_uid);

  INSERT INTO public.notificaciones_usuario (usuario_id, tipo, titulo, mensaje, metadata)
  VALUES (
    v_aviso.usuario_id,
    'cupo_interes',
    'Alguien respondió a tu aviso',
    v_display || ' quiere contactarte sobre tu aviso de cupo.',
    jsonb_build_object('aviso_id', p_aviso_id, 'evento_id', v_aviso.evento_id, 'interes_id', v_interes_id)
  );

  RETURN jsonb_build_object('ok', true, 'interes_id', v_interes_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.cerrar_aviso_cupo(p_aviso_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Debes iniciar sesión');
  END IF;

  UPDATE public.avisos_cupo
  SET estado = 'cerrado', fecha_cierre = now()
  WHERE id = p_aviso_id AND usuario_id = v_uid AND estado = 'activo';

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No se pudo cerrar el aviso');
  END IF;

  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.reportar_aviso_cupo(
  p_aviso_id BIGINT,
  p_motivo TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_reportes INT;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Debes iniciar sesión');
  END IF;

  INSERT INTO public.reportes_cupo (aviso_id, usuario_id, motivo)
  VALUES (p_aviso_id, v_uid, nullif(trim(p_motivo), ''))
  ON CONFLICT (aviso_id, usuario_id) DO NOTHING;

  SELECT count(*)::int INTO v_reportes FROM public.reportes_cupo WHERE aviso_id = p_aviso_id;

  IF v_reportes >= 3 THEN
    UPDATE public.avisos_cupo SET estado = 'oculto', fecha_cierre = now() WHERE id = p_aviso_id;
  END IF;

  RETURN jsonb_build_object('ok', true, 'reportes', v_reportes);
END;
$$;

CREATE OR REPLACE FUNCTION public.listar_intereses_mi_aviso(p_aviso_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.avisos_cupo a WHERE a.id = p_aviso_id AND a.usuario_id = v_uid) THEN
    RETURN '[]'::jsonb;
  END IF;

  RETURN (
    SELECT coalesce(jsonb_agg(row_to_json(t)::jsonb ORDER BY t.fecha_creacion DESC), '[]'::jsonb)
    FROM (
      SELECT
        i.id,
        i.mensaje,
        i.estado,
        i.fecha_creacion,
        public.fn_autor_display(i.usuario_id) AS interesado_display,
        u.email AS interesado_email
      FROM public.intereses_cupo i
      JOIN public.usuarios u ON u.id = i.usuario_id
      WHERE i.aviso_id = p_aviso_id
        AND i.estado <> 'cerrado'
    ) t
  );
END;
$$;

-- ─── RPC: explorar avisos de todos los eventos ────────────────────────────

CREATE OR REPLACE FUNCTION public.listar_avisos_cupo_global(
  p_tipo TEXT DEFAULT NULL,
  p_limite INTEGER DEFAULT 80,
  p_offset INTEGER DEFAULT 0
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result JSONB;
  v_limite INT;
  v_offset INT;
BEGIN
  v_limite := least(greatest(coalesce(p_limite, 80), 1), 100);
  v_offset := greatest(coalesce(p_offset, 0), 0);

  SELECT coalesce(jsonb_agg(row_to_json(t)::jsonb ORDER BY t.fecha_creacion DESC), '[]'::jsonb)
  INTO v_result
  FROM (
    SELECT
      a.id,
      a.evento_id,
      e.titulo AS evento_titulo,
      e.imagen_principal AS evento_imagen_principal,
      e.fecha_inicio AS evento_fecha_inicio,
      a.tipo,
      a.descripcion,
      a.cupos,
      a.zona_texto,
      a.precio_referencia_cop,
      a.autor_display,
      a.fecha_creacion,
      (SELECT count(*)::int FROM public.intereses_cupo i WHERE i.aviso_id = a.id AND i.estado <> 'cerrado') AS intereses_count,
      (public.fn_usuario_id_actual() IS NOT NULL AND a.usuario_id = public.fn_usuario_id_actual()) AS es_mio
    FROM public.avisos_cupo a
    JOIN public.eventos e ON e.id = a.evento_id
    WHERE a.estado = 'activo'
      AND e.activo = true
      AND (p_tipo IS NULL OR a.tipo = p_tipo)
    ORDER BY a.fecha_creacion DESC
    LIMIT v_limite
    OFFSET v_offset
  ) t;

  RETURN v_result;
END;
$$;

-- ─── RPC: vista global Mis cupos ────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.resumen_mis_cupos()
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_avisos INT;
  v_respuestas INT;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('avisos_activos', 0, 'total_respuestas', 0);
  END IF;

  SELECT
    count(*)::int,
    coalesce(sum(sub.cnt), 0)::int
  INTO v_avisos, v_respuestas
  FROM public.avisos_cupo a
  LEFT JOIN LATERAL (
    SELECT count(*)::int AS cnt
    FROM public.intereses_cupo i
    WHERE i.aviso_id = a.id AND i.estado <> 'cerrado'
  ) sub ON true
  WHERE a.usuario_id = v_uid AND a.estado = 'activo';

  RETURN jsonb_build_object(
    'avisos_activos', coalesce(v_avisos, 0),
    'total_respuestas', coalesce(v_respuestas, 0)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.listar_mis_avisos_cupo()
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_result JSONB;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  SELECT coalesce(jsonb_agg(row_to_json(t)::jsonb ORDER BY t.fecha_creacion DESC), '[]'::jsonb)
  INTO v_result
  FROM (
    SELECT
      a.id,
      a.evento_id,
      e.titulo AS evento_titulo,
      e.imagen_principal AS evento_imagen_principal,
      e.fecha_inicio AS evento_fecha_inicio,
      a.tipo,
      a.descripcion,
      a.cupos,
      a.zona_texto,
      a.precio_referencia_cop,
      a.autor_display,
      a.fecha_creacion,
      (SELECT count(*)::int FROM public.intereses_cupo i WHERE i.aviso_id = a.id AND i.estado <> 'cerrado') AS intereses_count,
      true AS es_mio
    FROM public.avisos_cupo a
    JOIN public.eventos e ON e.id = a.evento_id
    WHERE a.usuario_id = v_uid
      AND a.estado = 'activo'
  ) t;

  RETURN v_result;
END;
$$;

-- ─── Permisos RPC ───────────────────────────────────────────────────────────

GRANT EXECUTE ON FUNCTION public.listar_avisos_cupo_evento(BIGINT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.crear_aviso_cupo(BIGINT, TEXT, TEXT, INTEGER, TEXT, BIGINT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_interes_cupo(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cerrar_aviso_cupo(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reportar_aviso_cupo(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.listar_intereses_mi_aviso(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.listar_avisos_cupo_global(TEXT, INTEGER, INTEGER) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.resumen_mis_cupos() TO authenticated;
GRANT EXECUTE ON FUNCTION public.listar_mis_avisos_cupo() TO authenticated;
