-- ============================================================
-- 014_modulo_covers.sql
-- Módulo Covers Eventum: checkout independiente (compras_cover),
-- tipos, plantillas, sesiones, boletas_cover con QR propio, aforo/puerta.
-- Idempotente (IF NOT EXISTS, CREATE OR REPLACE, DROP IF EXISTS).
-- Requiere: lugares, usuarios, wompi_cuentas, cupones_descuento,
--           transacciones_checkout; fn_usuario_id_actual (011).
-- ============================================================

-- ─── Lugares: flag visita 360 ───────────────────────────────────────────────

ALTER TABLE public.lugares
  ADD COLUMN IF NOT EXISTS covers_habilitado BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE public.lugares
  ADD COLUMN IF NOT EXISTS covers_descripcion TEXT;

ALTER TABLE public.lugares
  ADD COLUMN IF NOT EXISTS covers_porcentaje_servicio NUMERIC(5, 2) NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.lugares.covers_porcentaje_servicio IS
  'Porcentaje de servicio Eventum sobre ventas online de covers en este lugar (como eventos.porcentaje_servicio).';

COMMENT ON COLUMN public.lugares.covers_habilitado IS
  'Si true, el lugar expone ficha pública de covers (módulo Covers Eventum).';

-- Checkout unificado: tipos cover y cover_mixto (venta online vía carrito/Wompi).
ALTER TABLE public.transacciones_checkout
  DROP CONSTRAINT IF EXISTS transacciones_checkout_tipo_check;

ALTER TABLE public.transacciones_checkout
  ADD CONSTRAINT transacciones_checkout_tipo_check
  CHECK (tipo IN ('boletas', 'productos', 'mixto', 'cover', 'cover_mixto'));

ALTER TABLE public.transacciones_checkout
  ADD COLUMN IF NOT EXISTS lugar_id BIGINT REFERENCES public.lugares(id) ON DELETE SET NULL;

ALTER TABLE public.transacciones_checkout
  ADD COLUMN IF NOT EXISTS compra_cover_id BIGINT;

ALTER TABLE public.transacciones_checkout
  ALTER COLUMN evento_id DROP NOT NULL;

COMMENT ON COLUMN public.transacciones_checkout.tipo IS
  'boletas | productos | mixto | cover (solo cover) | cover_mixto (cover + productos)';

-- ─── Tablas ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.tipos_cover (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lugar_id BIGINT NOT NULL REFERENCES public.lugares(id) ON DELETE CASCADE,
  organizador_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  nombre TEXT NOT NULL CHECK (char_length(trim(nombre)) >= 2),
  descripcion TEXT,
  precio_cop BIGINT NOT NULL CHECK (precio_cop >= 0),
  permite_reingreso BOOLEAN NOT NULL DEFAULT true,
  limite_por_persona INTEGER CHECK (limite_por_persona IS NULL OR limite_por_persona >= 1),
  orden INTEGER NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT true,
  wompi_cuenta_id BIGINT REFERENCES public.wompi_cuentas(id) ON DELETE SET NULL,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tipos_cover_lugar_activo
  ON public.tipos_cover(lugar_id, orden)
  WHERE activo = true;

CREATE INDEX IF NOT EXISTS idx_tipos_cover_organizador
  ON public.tipos_cover(organizador_id, fecha_creacion DESC);

CREATE TABLE IF NOT EXISTS public.plantillas_cover (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_cover_id BIGINT NOT NULL REFERENCES public.tipos_cover(id) ON DELETE CASCADE,
  lugar_id BIGINT NOT NULL REFERENCES public.lugares(id) ON DELETE CASCADE,
  -- ISO 8601: 1 = lunes … 7 = domingo
  dia_semana SMALLINT NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
  hora_apertura TIME NOT NULL,
  hora_cierre TIME NOT NULL,
  aforo_maximo INTEGER CHECK (aforo_maximo IS NULL OR aforo_maximo >= 1),
  cantidad_maxima_venta INTEGER CHECK (cantidad_maxima_venta IS NULL OR cantidad_maxima_venta >= 0),
  -- Cuántos días hacia adelante generar sesiones automáticas.
  dias_anticipacion INTEGER NOT NULL DEFAULT 21 CHECK (dias_anticipacion BETWEEN 1 AND 90),
  activo BOOLEAN NOT NULL DEFAULT true,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_plantillas_cover_tipo
  ON public.plantillas_cover(tipo_cover_id)
  WHERE activo = true;

CREATE INDEX IF NOT EXISTS idx_plantillas_cover_lugar_dia
  ON public.plantillas_cover(lugar_id, dia_semana)
  WHERE activo = true;

-- Horario plantilla: permite cruce de medianoche (22:00 → 03:00). Re-ejecutable.
ALTER TABLE public.plantillas_cover DROP CONSTRAINT IF EXISTS plantillas_cover_check;
ALTER TABLE public.plantillas_cover
  ADD CONSTRAINT plantillas_cover_check
  CHECK (hora_cierre IS DISTINCT FROM hora_apertura);

CREATE TABLE IF NOT EXISTS public.sesiones_cover (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plantilla_cover_id BIGINT REFERENCES public.plantillas_cover(id) ON DELETE SET NULL,
  tipo_cover_id BIGINT NOT NULL REFERENCES public.tipos_cover(id) ON DELETE RESTRICT,
  lugar_id BIGINT NOT NULL REFERENCES public.lugares(id) ON DELETE CASCADE,
  organizador_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  fecha DATE NOT NULL,
  hora_apertura TIMESTAMPTZ NOT NULL,
  hora_cierre TIMESTAMPTZ NOT NULL,
  precio_cop BIGINT NOT NULL CHECK (precio_cop >= 0),
  aforo_maximo INTEGER NOT NULL CHECK (aforo_maximo >= 1),
  personas_dentro INTEGER NOT NULL DEFAULT 0 CHECK (personas_dentro >= 0),
  cantidad_vendida INTEGER NOT NULL DEFAULT 0 CHECK (cantidad_vendida >= 0),
  cantidad_maxima_venta INTEGER CHECK (cantidad_maxima_venta IS NULL OR cantidad_maxima_venta >= 0),
  estado TEXT NOT NULL DEFAULT 'programada'
    CHECK (estado IN ('programada', 'abierta', 'cerrada', 'cancelada')),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (tipo_cover_id, fecha),
  CHECK (hora_cierre > hora_apertura),
  CHECK (personas_dentro <= aforo_maximo)
);

CREATE INDEX IF NOT EXISTS idx_sesiones_cover_lugar_fecha
  ON public.sesiones_cover(lugar_id, fecha DESC);

CREATE INDEX IF NOT EXISTS idx_sesiones_cover_estado_abierta
  ON public.sesiones_cover(lugar_id, estado)
  WHERE estado = 'abierta';

CREATE INDEX IF NOT EXISTS idx_sesiones_cover_plantilla
  ON public.sesiones_cover(plantilla_cover_id)
  WHERE plantilla_cover_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.compras_cover (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  lugar_id BIGINT NOT NULL REFERENCES public.lugares(id) ON DELETE RESTRICT,
  numero_transaccion TEXT NOT NULL UNIQUE,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  descuento_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  porcentaje_servicio NUMERIC(5,2) NOT NULL DEFAULT 0,
  valor_servicio NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  cupon_id BIGINT REFERENCES public.cupones_descuento(id) ON DELETE SET NULL,
  estado_pago TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado_pago IN ('pendiente', 'completado', 'fallido')),
  estado_compra TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado_compra IN ('pendiente', 'confirmada', 'cancelada')),
  wompi_cuenta_id BIGINT REFERENCES public.wompi_cuentas(id) ON DELETE SET NULL,
  wompi_transaction_id TEXT,
  wompi_reference TEXT,
  wompi_status TEXT,
  metodo_pago TEXT,
  fecha_compra TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_confirmacion TIMESTAMPTZ,
  fecha_cancelacion TIMESTAMPTZ,
  motivo_cancelacion TEXT,
  transaccion_checkout_id BIGINT REFERENCES public.transacciones_checkout(id) ON DELETE SET NULL,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_compras_cover_cliente
  ON public.compras_cover(cliente_id, fecha_compra DESC);

CREATE INDEX IF NOT EXISTS idx_compras_cover_lugar
  ON public.compras_cover(lugar_id, fecha_compra DESC);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'transacciones_checkout_compra_cover_id_fkey'
  ) THEN
    ALTER TABLE public.transacciones_checkout
      ADD CONSTRAINT transacciones_checkout_compra_cover_id_fkey
      FOREIGN KEY (compra_cover_id) REFERENCES public.compras_cover(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.boletas_cover (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_cover_id BIGINT NOT NULL REFERENCES public.compras_cover(id) ON DELETE CASCADE,
  sesion_cover_id BIGINT NOT NULL REFERENCES public.sesiones_cover(id) ON DELETE RESTRICT,
  tipo_cover_id BIGINT NOT NULL REFERENCES public.tipos_cover(id) ON DELETE RESTRICT,
  codigo_qr TEXT,
  precio_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
  estado TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'activa', 'cancelada', 'consumida')),
  estado_acceso TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado_acceso IN ('pendiente', 'dentro', 'fuera', 'consumida')),
  titular_cliente_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
  primera_entrada_at TIMESTAMPTZ,
  ultima_entrada_at TIMESTAMPTZ,
  ultima_salida_at TIMESTAMPTZ,
  entradas_count INTEGER NOT NULL DEFAULT 0 CHECK (entradas_count >= 0),
  salidas_count INTEGER NOT NULL DEFAULT 0 CHECK (salidas_count >= 0),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_boletas_cover_codigo_qr
  ON public.boletas_cover(codigo_qr)
  WHERE codigo_qr IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_boletas_cover_compra
  ON public.boletas_cover(compra_cover_id)
  WHERE compra_cover_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_boletas_cover_sesion
  ON public.boletas_cover(sesion_cover_id, estado_acceso);

ALTER TABLE public.boletas_cover
  ADD COLUMN IF NOT EXISTS titular_cliente_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL;

UPDATE public.boletas_cover bc
SET titular_cliente_id = cc.cliente_id
FROM public.compras_cover cc
WHERE cc.id = bc.compra_cover_id
  AND bc.titular_cliente_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_boletas_cover_titular
  ON public.boletas_cover(titular_cliente_id)
  WHERE titular_cliente_id IS NOT NULL;

-- ─── Traslados cover (reutiliza traslados_boleta de palcos) ───────────────────

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'traslados_boleta'
  ) THEN
    CREATE TABLE public.traslados_boleta (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      boleta_id BIGINT REFERENCES public.boletas_compradas(id) ON DELETE CASCADE,
      boleta_cover_id BIGINT REFERENCES public.boletas_cover(id) ON DELETE CASCADE,
      usuario_origen_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
      usuario_destino_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
      email_destino TEXT NOT NULL,
      estado TEXT NOT NULL DEFAULT 'enviado'
        CHECK (estado IN ('enviado', 'recibido', 'aceptado', 'rechazado', 'cancelado')),
      fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
      fecha_recibido TIMESTAMPTZ,
      fecha_aceptacion TIMESTAMPTZ,
      fecha_rechazo TIMESTAMPTZ,
      fecha_cancelacion TIMESTAMPTZ,
      CONSTRAINT traslados_boleta_un_solo_destino CHECK (
        (boleta_id IS NOT NULL AND boleta_cover_id IS NULL)
        OR (boleta_id IS NULL AND boleta_cover_id IS NOT NULL)
      )
    );
  END IF;
END $$;

ALTER TABLE public.traslados_boleta
  ADD COLUMN IF NOT EXISTS boleta_cover_id BIGINT REFERENCES public.boletas_cover(id) ON DELETE CASCADE;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'traslados_boleta'
      AND column_name = 'boleta_id'
      AND is_nullable = 'NO'
  ) THEN
    ALTER TABLE public.traslados_boleta ALTER COLUMN boleta_id DROP NOT NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'traslados_boleta_un_solo_destino'
      AND conrelid = 'public.traslados_boleta'::regclass
  ) THEN
    ALTER TABLE public.traslados_boleta
      ADD CONSTRAINT traslados_boleta_un_solo_destino CHECK (
        (boleta_id IS NOT NULL AND boleta_cover_id IS NULL)
        OR (boleta_id IS NULL AND boleta_cover_id IS NOT NULL)
      );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_traslados_boleta_cover
  ON public.traslados_boleta(boleta_cover_id, estado)
  WHERE boleta_cover_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.accesos_cover (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  boleta_cover_id BIGINT NOT NULL REFERENCES public.boletas_cover(id) ON DELETE CASCADE,
  sesion_cover_id BIGINT NOT NULL REFERENCES public.sesiones_cover(id) ON DELETE CASCADE,
  tipo_movimiento TEXT NOT NULL CHECK (tipo_movimiento IN ('entrada', 'salida')),
  lector_usuario_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
  personas_dentro_despues INTEGER NOT NULL CHECK (personas_dentro_despues >= 0),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  notas TEXT
);

CREATE INDEX IF NOT EXISTS idx_accesos_cover_sesion_fecha
  ON public.accesos_cover(sesion_cover_id, fecha_creacion DESC);

CREATE INDEX IF NOT EXISTS idx_accesos_cover_boleta_cover
  ON public.accesos_cover(boleta_cover_id, fecha_creacion DESC);

-- ─── RLS ────────────────────────────────────────────────────────────────────

ALTER TABLE public.tipos_cover ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plantillas_cover ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sesiones_cover ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boletas_cover ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accesos_cover ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras_cover ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tipos_cover_select_publico ON public.tipos_cover;
CREATE POLICY tipos_cover_select_publico ON public.tipos_cover
  FOR SELECT TO anon, authenticated
  USING (
    activo = true
    AND EXISTS (
      SELECT 1 FROM public.lugares l
      WHERE l.id = tipos_cover.lugar_id
        AND l.activo = true
        AND l.covers_habilitado = true
    )
  );

DROP POLICY IF EXISTS sesiones_cover_select_publico ON public.sesiones_cover;
CREATE POLICY sesiones_cover_select_publico ON public.sesiones_cover
  FOR SELECT TO anon, authenticated
  USING (
    estado IN ('programada', 'abierta')
    AND EXISTS (
      SELECT 1 FROM public.lugares l
      WHERE l.id = sesiones_cover.lugar_id
        AND l.activo = true
        AND l.covers_habilitado = true
    )
  );

DROP POLICY IF EXISTS boletas_cover_select_titular ON public.boletas_cover;
CREATE POLICY boletas_cover_select_titular ON public.boletas_cover
  FOR SELECT TO authenticated
  USING (
    coalesce(titular_cliente_id, (
      SELECT cc.cliente_id FROM public.compras_cover cc WHERE cc.id = boletas_cover.compra_cover_id
    )) = public.fn_usuario_id_actual()
    OR EXISTS (
      SELECT 1 FROM public.compras_cover cc
      WHERE cc.id = boletas_cover.compra_cover_id
        AND cc.cliente_id = public.fn_usuario_id_actual()
    )
    OR EXISTS (
      SELECT 1 FROM public.traslados_boleta t
      WHERE t.boleta_cover_id = boletas_cover.id
        AND t.usuario_destino_id = public.fn_usuario_id_actual()
        AND t.estado IN ('enviado', 'recibido')
    )
  );

DROP POLICY IF EXISTS compras_cover_select_own ON public.compras_cover;
CREATE POLICY compras_cover_select_own ON public.compras_cover
  FOR SELECT TO authenticated
  USING (
    cliente_id = public.fn_usuario_id_actual()
    OR EXISTS (
      SELECT 1 FROM public.boletas_cover bc
      WHERE bc.compra_cover_id = compras_cover.id
        AND bc.titular_cliente_id = public.fn_usuario_id_actual()
    )
  );

DROP POLICY IF EXISTS compras_cover_all_service ON public.compras_cover;
CREATE POLICY compras_cover_all_service ON public.compras_cover
  FOR ALL TO service_role USING (true) WITH CHECK (true);

GRANT SELECT ON public.tipos_cover TO anon, authenticated;
GRANT SELECT ON public.sesiones_cover TO anon, authenticated;
GRANT SELECT ON public.boletas_cover TO authenticated;
GRANT SELECT ON public.compras_cover TO authenticated;
GRANT ALL ON public.compras_cover TO service_role;

-- Escritura vía RPC SECURITY DEFINER (plantillas/accesos no expuestos directo al cliente).

-- ─── Helpers ──────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.fn_usuario_es_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.auth_user_id = auth.uid()
      AND u.tipo_usuario_id = 3
      AND u.activo = true
  );
$$;

CREATE OR REPLACE FUNCTION public.fn_usuario_puede_gestionar_cover(p_organizador_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    public.fn_usuario_es_admin()
    OR EXISTS (
      SELECT 1 FROM public.usuarios u
      WHERE u.auth_user_id = auth.uid()
        AND u.id = p_organizador_id
        AND u.tipo_usuario_id = 2
        AND u.activo = true
    );
$$;

CREATE OR REPLACE FUNCTION public.fn_aforo_default_lugar(p_lugar_id BIGINT)
RETURNS INTEGER
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT greatest(coalesce(l.capacidad_maxima, 0), 1)::int
  FROM public.lugares l
  WHERE l.id = p_lugar_id;
$$;

-- Convierte fecha + horas TIME a TIMESTAMPTZ; si cierre < apertura, cierre es al día siguiente.
CREATE OR REPLACE FUNCTION public.fn_cover_horario_sesion(
  p_fecha DATE,
  p_hora_apertura TIME,
  p_hora_cierre TIME
)
RETURNS TABLE(hora_apertura_ts TIMESTAMPTZ, hora_cierre_ts TIMESTAMPTZ)
LANGUAGE plpgsql
IMMUTABLE
SET search_path = public
AS $$
BEGIN
  IF p_fecha IS NULL OR p_hora_apertura IS NULL OR p_hora_cierre IS NULL THEN
    RAISE EXCEPTION 'fecha, hora_apertura y hora_cierre son requeridos';
  END IF;

  IF p_hora_cierre = p_hora_apertura THEN
    RAISE EXCEPTION 'La hora de cierre debe ser distinta a la de apertura';
  END IF;

  hora_apertura_ts := (p_fecha + p_hora_apertura) AT TIME ZONE 'America/Bogota';

  IF p_hora_cierre > p_hora_apertura THEN
    hora_cierre_ts := (p_fecha + p_hora_cierre) AT TIME ZONE 'America/Bogota';
  ELSE
    hora_cierre_ts := ((p_fecha + 1) + p_hora_cierre) AT TIME ZONE 'America/Bogota';
  END IF;

  RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_generar_codigo_qr_cover()
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT 'C-' || replace(gen_random_uuid()::text, '-', '');
$$;

CREATE OR REPLACE FUNCTION public.fn_usuario_es_organizador()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.auth_user_id = auth.uid()
      AND u.tipo_usuario_id = 2
      AND u.activo = true
  );
$$;

CREATE OR REPLACE FUNCTION public.fn_usuario_puede_configurar_lugar_cover(p_lugar_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    public.fn_usuario_es_admin()
    OR (
      public.fn_usuario_es_organizador()
      AND (
        p_lugar_id IS NULL
        OR EXISTS (
          SELECT 1 FROM public.tipos_cover tc
          WHERE tc.lugar_id = p_lugar_id
            AND tc.organizador_id = public.fn_usuario_id_actual()
        )
        OR NOT EXISTS (
          SELECT 1 FROM public.tipos_cover tc WHERE tc.lugar_id = p_lugar_id
        )
      )
    );
$$;

-- ─── RPC: listados públicos (visita 360) ────────────────────────────────────

CREATE OR REPLACE FUNCTION public.listar_lugares_con_covers(
  p_limite INT DEFAULT 50,
  p_offset INT DEFAULT 0
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_limite INT;
  v_offset INT;
  v_result JSONB;
BEGIN
  v_limite := least(greatest(coalesce(p_limite, 50), 1), 100);
  v_offset := greatest(coalesce(p_offset, 0), 0);

  SELECT coalesce(jsonb_agg(row_to_json(t)::jsonb ORDER BY t.nombre), '[]'::jsonb)
  INTO v_result
  FROM (
    SELECT
      l.id,
      l.nombre,
      l.direccion,
      l.ciudad,
      l.pais,
      l.imagen_principal,
      l.capacidad_maxima,
      l.covers_descripcion,
      (
        SELECT count(*)::int
        FROM public.tipos_cover tc
        WHERE tc.lugar_id = l.id AND tc.activo = true
      ) AS tipos_cover_count,
      (
        SELECT min(sc.hora_apertura)
        FROM public.sesiones_cover sc
        WHERE sc.lugar_id = l.id
          AND sc.fecha = current_date
          AND sc.estado IN ('programada', 'abierta')
      ) AS cover_hoy_apertura,
      (
        SELECT min(sc.precio_cop)
        FROM public.sesiones_cover sc
        WHERE sc.lugar_id = l.id
          AND sc.fecha >= current_date
          AND sc.estado IN ('programada', 'abierta')
      ) AS precio_desde_cop
    FROM public.lugares l
    WHERE l.activo = true
      AND l.covers_habilitado = true
      AND EXISTS (
        SELECT 1 FROM public.tipos_cover tc
        WHERE tc.lugar_id = l.id AND tc.activo = true
      )
    ORDER BY l.nombre
    LIMIT v_limite OFFSET v_offset
  ) t;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.obtener_lugar_cover(p_lugar_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lugar JSONB;
  v_tipos JSONB;
  v_sesiones JSONB;
BEGIN
  IF p_lugar_id IS NULL OR p_lugar_id <= 0 THEN
    RETURN NULL;
  END IF;

  SELECT row_to_json(l)::jsonb
  INTO v_lugar
  FROM (
    SELECT
      l.id,
      l.nombre,
      l.direccion,
      l.ciudad,
      l.pais,
      l.capacidad_maxima,
      l.imagen_principal,
      l.descripcion,
      l.covers_descripcion,
      l.latitud,
      l.longitud,
      l.telefono,
      l.sitio_web,
      l.covers_porcentaje_servicio
    FROM public.lugares l
    WHERE l.id = p_lugar_id
      AND l.activo = true
      AND l.covers_habilitado = true
  ) l;

  IF v_lugar IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT coalesce(jsonb_agg(row_to_json(t)::jsonb ORDER BY t.orden, t.nombre), '[]'::jsonb)
  INTO v_tipos
  FROM (
    SELECT
      tc.id,
      tc.nombre,
      tc.descripcion,
      tc.precio_cop,
      tc.permite_reingreso,
      tc.limite_por_persona,
      tc.orden,
      tc.wompi_cuenta_id
    FROM public.tipos_cover tc
    WHERE tc.lugar_id = p_lugar_id
      AND tc.activo = true
  ) t;

  SELECT coalesce(jsonb_agg(row_to_json(s)::jsonb ORDER BY s.fecha, s.hora_apertura), '[]'::jsonb)
  INTO v_sesiones
  FROM (
    SELECT
      sc.id,
      sc.tipo_cover_id,
      tc.nombre AS tipo_cover_nombre,
      sc.fecha,
      sc.hora_apertura,
      sc.hora_cierre,
      sc.precio_cop,
      sc.aforo_maximo,
      sc.personas_dentro,
      sc.cantidad_vendida,
      sc.cantidad_maxima_venta,
      sc.estado,
      tc.wompi_cuenta_id,
      greatest(0, sc.aforo_maximo - sc.personas_dentro) AS cupos_dentro_disponibles,
      CASE
        WHEN sc.cantidad_maxima_venta IS NULL THEN NULL
        ELSE greatest(0, sc.cantidad_maxima_venta - sc.cantidad_vendida)
      END AS cupos_venta_disponibles
    FROM public.sesiones_cover sc
    JOIN public.tipos_cover tc ON tc.id = sc.tipo_cover_id
    WHERE sc.lugar_id = p_lugar_id
      AND sc.fecha >= current_date
      AND sc.estado IN ('programada', 'abierta')
      AND tc.activo = true
  ) s;

  RETURN jsonb_build_object(
    'lugar', v_lugar,
    'tipos_cover', v_tipos,
    'sesiones', v_sesiones
  );
END;
$$;

-- ─── RPC: configuración del lugar (panel admin) ─────────────────────────────

CREATE OR REPLACE FUNCTION public.configurar_lugar_cover(
  p_lugar_id BIGINT,
  p_covers_habilitado BOOLEAN DEFAULT true,
  p_covers_descripcion TEXT DEFAULT NULL,
  p_covers_porcentaje_servicio NUMERIC DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.lugares%ROWTYPE;
BEGIN
  IF p_lugar_id IS NULL OR p_lugar_id <= 0 THEN
    RAISE EXCEPTION 'lugar_id requerido';
  END IF;

  IF NOT public.fn_usuario_puede_configurar_lugar_cover(p_lugar_id) THEN
    RAISE EXCEPTION 'Sin permiso para configurar covers en este lugar';
  END IF;

  UPDATE public.lugares
  SET
    covers_habilitado = coalesce(p_covers_habilitado, covers_habilitado),
    covers_descripcion = CASE
      WHEN p_covers_descripcion IS NULL THEN covers_descripcion
      ELSE nullif(trim(p_covers_descripcion), '')
    END,
    covers_porcentaje_servicio = CASE
      WHEN p_covers_porcentaje_servicio IS NULL THEN covers_porcentaje_servicio
      ELSE least(100, greatest(0, p_covers_porcentaje_servicio))
    END
  WHERE id = p_lugar_id
  RETURNING * INTO v_row;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Lugar no encontrado';
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'lugar_id', v_row.id,
    'covers_habilitado', v_row.covers_habilitado,
    'covers_descripcion', v_row.covers_descripcion,
    'covers_porcentaje_servicio', v_row.covers_porcentaje_servicio
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.obtener_config_cover_lugar(p_lugar_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lugar JSONB;
  v_tipos JSONB;
  v_plantillas JSONB;
  v_sesiones JSONB;
BEGIN
  IF p_lugar_id IS NULL OR p_lugar_id <= 0 THEN
    RETURN NULL;
  END IF;

  IF NOT public.fn_usuario_puede_configurar_lugar_cover(p_lugar_id) THEN
    RAISE EXCEPTION 'Sin permiso';
  END IF;

  SELECT row_to_json(l)::jsonb INTO v_lugar
  FROM (
    SELECT
      l.id,
      l.nombre,
      l.direccion,
      l.ciudad,
      l.capacidad_maxima,
      l.covers_habilitado,
      l.covers_descripcion,
      l.covers_porcentaje_servicio,
      l.activo
    FROM public.lugares l
    WHERE l.id = p_lugar_id
  ) l;

  IF v_lugar IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT coalesce(jsonb_agg(row_to_json(t)::jsonb ORDER BY t.orden, t.nombre), '[]'::jsonb)
  INTO v_tipos
  FROM (
    SELECT tc.*
    FROM public.tipos_cover tc
    WHERE tc.lugar_id = p_lugar_id
  ) t;

  SELECT coalesce(jsonb_agg(row_to_json(p)::jsonb ORDER BY p.dia_semana, p.hora_apertura), '[]'::jsonb)
  INTO v_plantillas
  FROM (
    SELECT
      pl.*,
      tc.nombre AS tipo_cover_nombre
    FROM public.plantillas_cover pl
    JOIN public.tipos_cover tc ON tc.id = pl.tipo_cover_id
    WHERE pl.lugar_id = p_lugar_id
  ) p;

  SELECT coalesce(jsonb_agg(row_to_json(s)::jsonb ORDER BY s.fecha DESC, s.hora_apertura), '[]'::jsonb)
  INTO v_sesiones
  FROM (
    SELECT
      sc.*,
      tc.nombre AS tipo_cover_nombre
    FROM public.sesiones_cover sc
    JOIN public.tipos_cover tc ON tc.id = sc.tipo_cover_id
    WHERE sc.lugar_id = p_lugar_id
      AND sc.fecha >= current_date - 7
  ) s;

  RETURN jsonb_build_object(
    'lugar', v_lugar,
    'tipos_cover', v_tipos,
    'plantillas_cover', v_plantillas,
    'sesiones_cover', v_sesiones
  );
END;
$$;

-- ─── RPC: gestión organizador ───────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.upsert_tipo_cover(
  p_id BIGINT DEFAULT NULL,
  p_lugar_id BIGINT DEFAULT NULL,
  p_nombre TEXT DEFAULT NULL,
  p_descripcion TEXT DEFAULT NULL,
  p_precio_cop BIGINT DEFAULT NULL,
  p_permite_reingreso BOOLEAN DEFAULT true,
  p_limite_por_persona INTEGER DEFAULT NULL,
  p_orden INTEGER DEFAULT 0,
  p_activo BOOLEAN DEFAULT true,
  p_wompi_cuenta_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_row public.tipos_cover%ROWTYPE;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Sesión requerida';
  END IF;

  IF p_id IS NULL THEN
    IF p_lugar_id IS NULL OR p_nombre IS NULL OR p_precio_cop IS NULL THEN
      RAISE EXCEPTION 'lugar_id, nombre y precio_cop son requeridos';
    END IF;
    IF NOT public.fn_usuario_puede_gestionar_cover(v_uid) THEN
      RAISE EXCEPTION 'Sin permiso para crear tipos cover';
    END IF;

    INSERT INTO public.tipos_cover (
      lugar_id, organizador_id, nombre, descripcion, precio_cop,
      permite_reingreso, limite_por_persona, orden, activo, wompi_cuenta_id
    ) VALUES (
      p_lugar_id, v_uid, trim(p_nombre), nullif(trim(p_descripcion), ''),
      p_precio_cop, coalesce(p_permite_reingreso, true), p_limite_por_persona,
      coalesce(p_orden, 0), coalesce(p_activo, true), p_wompi_cuenta_id
    )
    RETURNING * INTO v_row;

    UPDATE public.lugares
    SET covers_habilitado = true
    WHERE id = p_lugar_id;
  ELSE
    SELECT * INTO v_row FROM public.tipos_cover WHERE id = p_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Tipo cover no encontrado';
    END IF;
    IF NOT public.fn_usuario_puede_gestionar_cover(v_row.organizador_id) THEN
      RAISE EXCEPTION 'Sin permiso para editar este tipo cover';
    END IF;

    UPDATE public.tipos_cover
    SET
      nombre = coalesce(nullif(trim(p_nombre), ''), nombre),
      descripcion = CASE WHEN p_descripcion IS NULL THEN descripcion ELSE nullif(trim(p_descripcion), '') END,
      precio_cop = coalesce(p_precio_cop, precio_cop),
      permite_reingreso = coalesce(p_permite_reingreso, permite_reingreso),
      limite_por_persona = coalesce(p_limite_por_persona, limite_por_persona),
      orden = coalesce(p_orden, orden),
      activo = coalesce(p_activo, activo),
      wompi_cuenta_id = coalesce(p_wompi_cuenta_id, wompi_cuenta_id),
      fecha_actualizacion = now()
    WHERE id = p_id
    RETURNING * INTO v_row;
  END IF;

  RETURN row_to_json(v_row)::jsonb;
END;
$$;

CREATE OR REPLACE FUNCTION public.upsert_plantilla_cover(
  p_id BIGINT DEFAULT NULL,
  p_tipo_cover_id BIGINT DEFAULT NULL,
  p_dia_semana SMALLINT DEFAULT NULL,
  p_hora_apertura TIME DEFAULT NULL,
  p_hora_cierre TIME DEFAULT NULL,
  p_aforo_maximo INTEGER DEFAULT NULL,
  p_cantidad_maxima_venta INTEGER DEFAULT NULL,
  p_dias_anticipacion INTEGER DEFAULT 21,
  p_activo BOOLEAN DEFAULT true
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tipo public.tipos_cover%ROWTYPE;
  v_row public.plantillas_cover%ROWTYPE;
BEGIN
  IF public.fn_usuario_id_actual() IS NULL THEN
    RAISE EXCEPTION 'Sesión requerida';
  END IF;

  IF p_id IS NULL THEN
    SELECT * INTO v_tipo FROM public.tipos_cover WHERE id = p_tipo_cover_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Tipo cover no encontrado';
    END IF;
    IF NOT public.fn_usuario_puede_gestionar_cover(v_tipo.organizador_id) THEN
      RAISE EXCEPTION 'Sin permiso';
    END IF;
    IF p_dia_semana IS NULL OR p_hora_apertura IS NULL OR p_hora_cierre IS NULL THEN
      RAISE EXCEPTION 'dia_semana, hora_apertura y hora_cierre son requeridos';
    END IF;

    IF p_hora_cierre = p_hora_apertura THEN
      RAISE EXCEPTION 'La hora de cierre debe ser distinta a la de apertura';
    END IF;

    INSERT INTO public.plantillas_cover (
      tipo_cover_id, lugar_id, dia_semana, hora_apertura, hora_cierre,
      aforo_maximo, cantidad_maxima_venta, dias_anticipacion, activo
    ) VALUES (
      v_tipo.id, v_tipo.lugar_id, p_dia_semana, p_hora_apertura, p_hora_cierre,
      p_aforo_maximo, p_cantidad_maxima_venta,
      coalesce(p_dias_anticipacion, 21), coalesce(p_activo, true)
    )
    RETURNING * INTO v_row;
  ELSE
    SELECT * INTO v_row FROM public.plantillas_cover WHERE id = p_id;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Plantilla no encontrada';
    END IF;

    IF NOT public.fn_usuario_puede_gestionar_cover(
      (SELECT organizador_id FROM public.tipos_cover WHERE id = v_row.tipo_cover_id)
    ) THEN
      RAISE EXCEPTION 'Sin permiso';
    END IF;

    IF coalesce(p_hora_apertura, v_row.hora_apertura) = coalesce(p_hora_cierre, v_row.hora_cierre) THEN
      RAISE EXCEPTION 'La hora de cierre debe ser distinta a la de apertura';
    END IF;

    UPDATE public.plantillas_cover
    SET
      dia_semana = coalesce(p_dia_semana, dia_semana),
      hora_apertura = coalesce(p_hora_apertura, hora_apertura),
      hora_cierre = coalesce(p_hora_cierre, hora_cierre),
      aforo_maximo = coalesce(p_aforo_maximo, aforo_maximo),
      cantidad_maxima_venta = coalesce(p_cantidad_maxima_venta, cantidad_maxima_venta),
      dias_anticipacion = coalesce(p_dias_anticipacion, dias_anticipacion),
      activo = coalesce(p_activo, activo),
      fecha_actualizacion = now()
    WHERE id = p_id
    RETURNING * INTO v_row;
  END IF;

  RETURN row_to_json(v_row)::jsonb;
END;
$$;

CREATE OR REPLACE FUNCTION public.crear_sesion_cover_manual(
  p_tipo_cover_id BIGINT,
  p_fecha DATE,
  p_hora_apertura TIME,
  p_hora_cierre TIME,
  p_aforo_maximo INTEGER DEFAULT NULL,
  p_cantidad_maxima_venta INTEGER DEFAULT NULL,
  p_precio_cop BIGINT DEFAULT NULL,
  p_estado TEXT DEFAULT 'programada'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tipo public.tipos_cover%ROWTYPE;
  v_row public.sesiones_cover%ROWTYPE;
  v_aforo INT;
  v_apertura_ts TIMESTAMPTZ;
  v_cierre_ts TIMESTAMPTZ;
BEGIN
  SELECT * INTO v_tipo FROM public.tipos_cover WHERE id = p_tipo_cover_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tipo cover no encontrado';
  END IF;

  IF NOT public.fn_usuario_puede_gestionar_cover(v_tipo.organizador_id) THEN
    RAISE EXCEPTION 'Sin permiso';
  END IF;

  IF p_fecha IS NULL OR p_hora_apertura IS NULL OR p_hora_cierre IS NULL THEN
    RAISE EXCEPTION 'fecha, hora_apertura y hora_cierre son requeridos';
  END IF;

  IF p_estado NOT IN ('programada', 'abierta') THEN
    RAISE EXCEPTION 'estado inicial debe ser programada o abierta';
  END IF;

  v_aforo := coalesce(p_aforo_maximo, public.fn_aforo_default_lugar(v_tipo.lugar_id));

  IF EXISTS (
    SELECT 1 FROM public.sesiones_cover sc
    WHERE sc.tipo_cover_id = v_tipo.id AND sc.fecha = p_fecha
  ) THEN
    RAISE EXCEPTION 'Ya existe una sesión cover para ese tipo y fecha';
  END IF;

  SELECT h.hora_apertura_ts, h.hora_cierre_ts
  INTO v_apertura_ts, v_cierre_ts
  FROM public.fn_cover_horario_sesion(p_fecha, p_hora_apertura, p_hora_cierre) h;

  INSERT INTO public.sesiones_cover (
    plantilla_cover_id, tipo_cover_id, lugar_id, organizador_id,
    fecha, hora_apertura, hora_cierre, precio_cop, aforo_maximo,
    cantidad_maxima_venta, estado
  ) VALUES (
    NULL,
    v_tipo.id,
    v_tipo.lugar_id,
    v_tipo.organizador_id,
    p_fecha,
    v_apertura_ts,
    v_cierre_ts,
    coalesce(p_precio_cop, v_tipo.precio_cop),
    v_aforo,
    p_cantidad_maxima_venta,
    p_estado
  )
  RETURNING * INTO v_row;

  RETURN row_to_json(v_row)::jsonb;
END;
$$;

CREATE OR REPLACE FUNCTION public.actualizar_sesion_cover(
  p_sesion_id BIGINT,
  p_hora_apertura TIME DEFAULT NULL,
  p_hora_cierre TIME DEFAULT NULL,
  p_aforo_maximo INTEGER DEFAULT NULL,
  p_cantidad_maxima_venta INTEGER DEFAULT NULL,
  p_precio_cop BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sesion public.sesiones_cover%ROWTYPE;
  v_apertura_time TIME;
  v_cierre_time TIME;
  v_apertura_ts TIMESTAMPTZ;
  v_cierre_ts TIMESTAMPTZ;
BEGIN
  SELECT * INTO v_sesion FROM public.sesiones_cover WHERE id = p_sesion_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sesión no encontrada';
  END IF;

  IF NOT public.fn_usuario_puede_gestionar_cover(v_sesion.organizador_id) THEN
    RAISE EXCEPTION 'Sin permiso';
  END IF;

  IF v_sesion.estado NOT IN ('programada', 'abierta') THEN
    RAISE EXCEPTION 'Solo se editan sesiones programadas o abiertas';
  END IF;

  IF p_aforo_maximo IS NOT NULL AND p_aforo_maximo < v_sesion.personas_dentro THEN
    RAISE EXCEPTION 'El aforo no puede ser menor que personas dentro (%)', v_sesion.personas_dentro;
  END IF;

  v_apertura_time := coalesce(p_hora_apertura, v_sesion.hora_apertura::time);
  v_cierre_time := coalesce(p_hora_cierre, v_sesion.hora_cierre::time);

  IF p_hora_apertura IS NOT NULL OR p_hora_cierre IS NOT NULL THEN
    SELECT h.hora_apertura_ts, h.hora_cierre_ts
    INTO v_apertura_ts, v_cierre_ts
    FROM public.fn_cover_horario_sesion(v_sesion.fecha, v_apertura_time, v_cierre_time) h;
  END IF;

  UPDATE public.sesiones_cover
  SET
    hora_apertura = CASE
      WHEN p_hora_apertura IS NULL AND p_hora_cierre IS NULL THEN hora_apertura
      ELSE v_apertura_ts
    END,
    hora_cierre = CASE
      WHEN p_hora_apertura IS NULL AND p_hora_cierre IS NULL THEN hora_cierre
      ELSE v_cierre_ts
    END,
    aforo_maximo = coalesce(p_aforo_maximo, aforo_maximo),
    cantidad_maxima_venta = coalesce(p_cantidad_maxima_venta, cantidad_maxima_venta),
    precio_cop = coalesce(p_precio_cop, precio_cop),
    fecha_actualizacion = now()
  WHERE id = p_sesion_id
  RETURNING * INTO v_sesion;

  RETURN row_to_json(v_sesion)::jsonb;
END;
$$;

CREATE OR REPLACE FUNCTION public.inicializar_cover_lugar(
  p_lugar_id BIGINT,
  p_nombre_tipo TEXT,
  p_precio_cop BIGINT,
  p_dia_semana SMALLINT,
  p_hora_apertura TIME,
  p_hora_cierre TIME,
  p_covers_descripcion TEXT DEFAULT NULL,
  p_aforo_maximo INTEGER DEFAULT NULL,
  p_cantidad_maxima_venta INTEGER DEFAULT NULL,
  p_permite_reingreso BOOLEAN DEFAULT true,
  p_categoria_id BIGINT DEFAULT NULL,
  p_wompi_cuenta_id BIGINT DEFAULT NULL,
  p_generar_sesiones BOOLEAN DEFAULT true
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tipo JSONB;
  v_plantilla JSONB;
  v_generadas JSONB;
  v_tipo_id BIGINT;
BEGIN
  IF p_lugar_id IS NULL OR p_nombre_tipo IS NULL OR p_precio_cop IS NULL
     OR p_dia_semana IS NULL OR p_hora_apertura IS NULL OR p_hora_cierre IS NULL THEN
    RAISE EXCEPTION 'Parámetros obligatorios: lugar_id, nombre_tipo, precio_cop, dia_semana, horarios';
  END IF;

  PERFORM public.configurar_lugar_cover(p_lugar_id, true, p_covers_descripcion);

  v_tipo := public.upsert_tipo_cover(
    NULL, p_lugar_id, p_nombre_tipo, NULL, p_precio_cop,
    p_permite_reingreso, NULL, 0, true, p_wompi_cuenta_id
  );
  v_tipo_id := (v_tipo->>'id')::bigint;

  v_plantilla := public.upsert_plantilla_cover(
    NULL, v_tipo_id, p_dia_semana, p_hora_apertura, p_hora_cierre,
    p_aforo_maximo, p_cantidad_maxima_venta, 21, true
  );

  v_generadas := jsonb_build_object('sesiones_creadas', 0);
  IF coalesce(p_generar_sesiones, true) THEN
    v_generadas := public.generar_sesiones_cover_desde_plantillas(current_date + 21);
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'lugar_id', p_lugar_id,
    'tipo_cover', v_tipo,
    'plantilla_cover', v_plantilla,
    'sesiones', v_generadas,
    'config', public.obtener_config_cover_lugar(p_lugar_id)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.generar_sesiones_cover_desde_plantillas(
  p_hasta_fecha DATE DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_hasta DATE;
  v_creadas INT := 0;
  v_insertadas INT;
  rec RECORD;
  v_fecha DATE;
  v_aforo INT;
  v_apertura_ts TIMESTAMPTZ;
  v_cierre_ts TIMESTAMPTZ;
BEGIN
  IF NOT public.fn_usuario_es_admin()
     AND NOT EXISTS (
       SELECT 1 FROM public.usuarios u
       WHERE u.auth_user_id = auth.uid() AND u.tipo_usuario_id = 2 AND u.activo = true
     ) THEN
    RAISE EXCEPTION 'Sin permiso';
  END IF;

  v_hasta := coalesce(p_hasta_fecha, current_date + 21);

  FOR rec IN
    SELECT
      pl.*,
      tc.organizador_id,
      tc.precio_cop
    FROM public.plantillas_cover pl
    JOIN public.tipos_cover tc ON tc.id = pl.tipo_cover_id
    WHERE pl.activo = true
      AND tc.activo = true
  LOOP
    v_fecha := current_date;
    WHILE v_fecha <= v_hasta LOOP
      IF extract(isodow FROM v_fecha)::int = rec.dia_semana THEN
        v_aforo := coalesce(rec.aforo_maximo, public.fn_aforo_default_lugar(rec.lugar_id));

        SELECT h.hora_apertura_ts, h.hora_cierre_ts
        INTO v_apertura_ts, v_cierre_ts
        FROM public.fn_cover_horario_sesion(v_fecha, rec.hora_apertura, rec.hora_cierre) h;

        INSERT INTO public.sesiones_cover (
          plantilla_cover_id, tipo_cover_id, lugar_id, organizador_id,
          fecha, hora_apertura, hora_cierre, precio_cop, aforo_maximo,
          cantidad_maxima_venta, estado
        ) VALUES (
          rec.id,
          rec.tipo_cover_id,
          rec.lugar_id,
          rec.organizador_id,
          v_fecha,
          v_apertura_ts,
          v_cierre_ts,
          rec.precio_cop,
          v_aforo,
          rec.cantidad_maxima_venta,
          CASE WHEN v_fecha = current_date THEN 'abierta' ELSE 'programada' END
        )
        ON CONFLICT (tipo_cover_id, fecha) DO NOTHING;

        GET DIAGNOSTICS v_insertadas = ROW_COUNT;
        IF v_insertadas > 0 THEN
          v_creadas := v_creadas + 1;
        END IF;
      END IF;
      v_fecha := v_fecha + 1;
    END LOOP;
  END LOOP;

  RETURN jsonb_build_object('sesiones_creadas', v_creadas, 'hasta_fecha', v_hasta);
END;
$$;

CREATE OR REPLACE FUNCTION public.cambiar_estado_sesion_cover(
  p_sesion_id BIGINT,
  p_estado TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sesion public.sesiones_cover%ROWTYPE;
BEGIN
  IF p_estado NOT IN ('programada', 'abierta', 'cerrada', 'cancelada') THEN
    RAISE EXCEPTION 'Estado inválido';
  END IF;

  SELECT * INTO v_sesion FROM public.sesiones_cover WHERE id = p_sesion_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sesión no encontrada';
  END IF;

  IF NOT public.fn_usuario_puede_gestionar_cover(v_sesion.organizador_id) THEN
    RAISE EXCEPTION 'Sin permiso';
  END IF;

  UPDATE public.sesiones_cover
  SET estado = p_estado, fecha_actualizacion = now()
  WHERE id = p_sesion_id
  RETURNING * INTO v_sesion;

  IF p_estado = 'cerrada' THEN
    UPDATE public.boletas_cover bc
    SET
      estado_acceso = 'consumida',
      fecha_actualizacion = now()
    WHERE bc.sesion_cover_id = p_sesion_id
      AND bc.estado_acceso IN ('pendiente', 'fuera');
  END IF;

  RETURN row_to_json(v_sesion)::jsonb;
END;
$$;

-- ─── RPC: checkout independiente (compras_cover + boletas_cover) ──────────────

-- Parámetros obligatorios primero; opcionales con DEFAULT al final (regla PG 42P13).
DROP FUNCTION IF EXISTS public.crear_compra_cover_desde_pedido(
  BIGINT, BIGINT, JSONB, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, BIGINT, BIGINT, BIGINT, BOOLEAN
);

CREATE OR REPLACE FUNCTION public.crear_compra_cover_desde_pedido(
  p_cliente_id BIGINT,
  p_lugar_id BIGINT,
  p_items JSONB,
  p_subtotal NUMERIC,
  p_total NUMERIC,
  p_descuento_total NUMERIC DEFAULT 0,
  p_porcentaje_servicio NUMERIC DEFAULT 0,
  p_valor_servicio NUMERIC DEFAULT 0,
  p_cupon_id BIGINT DEFAULT NULL,
  p_wompi_cuenta_id BIGINT DEFAULT NULL,
  p_transaccion_checkout_id BIGINT DEFAULT NULL,
  p_confirmada BOOLEAN DEFAULT false
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_compra_id BIGINT;
  v_numero TEXT;
  v_item JSONB;
  v_sesion public.sesiones_cover%ROWTYPE;
  v_tipo_cover_id BIGINT;
  v_sesion_id BIGINT;
  v_cantidad INT;
  v_precio NUMERIC;
  v_i INT;
  v_bc public.boletas_cover%ROWTYPE;
  v_boletas JSONB := '[]'::jsonb;
  v_estado_pago TEXT;
  v_estado_compra TEXT;
  v_estado_boleta TEXT;
  v_now TIMESTAMPTZ := now();
BEGIN
  IF p_cliente_id IS NULL OR p_lugar_id IS NULL THEN
    RAISE EXCEPTION 'cliente_id y lugar_id son requeridos';
  END IF;

  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'items vacío';
  END IF;

  v_estado_pago := CASE WHEN p_confirmada THEN 'completado' ELSE 'pendiente' END;
  v_estado_compra := CASE WHEN p_confirmada THEN 'confirmada' ELSE 'pendiente' END;
  v_estado_boleta := CASE WHEN p_confirmada THEN 'activa' ELSE 'pendiente' END;

  v_numero := 'CCOV-' || to_char(v_now, 'YYYYMMDDHH24MISS') || '-' || floor(random() * 10000)::text;

  INSERT INTO public.compras_cover (
    cliente_id, lugar_id, numero_transaccion,
    subtotal, descuento_total, porcentaje_servicio, valor_servicio, total,
    cupon_id, estado_pago, estado_compra, wompi_cuenta_id,
    transaccion_checkout_id, fecha_confirmacion
  ) VALUES (
    p_cliente_id, p_lugar_id, v_numero,
    coalesce(p_subtotal, 0), coalesce(p_descuento_total, 0),
    coalesce(p_porcentaje_servicio, 0), coalesce(p_valor_servicio, 0), coalesce(p_total, 0),
    p_cupon_id, v_estado_pago, v_estado_compra, p_wompi_cuenta_id,
    p_transaccion_checkout_id,
    CASE WHEN p_confirmada THEN v_now ELSE NULL END
  )
  RETURNING id INTO v_compra_id;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_tipo_cover_id := (v_item->>'tipo_cover_id')::bigint;
    v_sesion_id := (v_item->>'sesion_cover_id')::bigint;
    v_cantidad := greatest(1, coalesce((v_item->>'cantidad')::int, 1));
    v_precio := coalesce((v_item->>'precio_unitario')::numeric, 0);

    SELECT * INTO v_sesion FROM public.sesiones_cover WHERE id = v_sesion_id FOR UPDATE;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Sesión cover % no encontrada', v_sesion_id;
    END IF;

    IF v_sesion.lugar_id IS DISTINCT FROM p_lugar_id THEN
      RAISE EXCEPTION 'Sesión % no pertenece al lugar %', v_sesion_id, p_lugar_id;
    END IF;

    IF v_sesion.tipo_cover_id IS DISTINCT FROM v_tipo_cover_id THEN
      RAISE EXCEPTION 'tipo_cover_id no coincide con la sesión %', v_sesion_id;
    END IF;

    IF v_sesion.estado NOT IN ('programada', 'abierta') THEN
      RAISE EXCEPTION 'Sesión % no disponible para venta', v_sesion_id;
    END IF;

    IF v_sesion.cantidad_maxima_venta IS NOT NULL
       AND v_sesion.cantidad_vendida + v_cantidad > v_sesion.cantidad_maxima_venta THEN
      RAISE EXCEPTION 'Cupo de venta agotado para sesión %', v_sesion_id;
    END IF;

    IF v_sesion.personas_dentro + v_cantidad > v_sesion.aforo_maximo THEN
      RAISE EXCEPTION 'Aforo insuficiente para sesión %', v_sesion_id;
    END IF;

    FOR v_i IN 1..v_cantidad LOOP
      INSERT INTO public.boletas_cover (
        compra_cover_id, sesion_cover_id, tipo_cover_id,
        codigo_qr, precio_unitario, estado, estado_acceso, titular_cliente_id
      ) VALUES (
        v_compra_id, v_sesion_id, v_tipo_cover_id,
        public.fn_generar_codigo_qr_cover(), v_precio, v_estado_boleta, 'pendiente', p_cliente_id
      )
      RETURNING * INTO v_bc;

      v_boletas := v_boletas || jsonb_build_array(jsonb_build_object(
        'id', v_bc.id,
        'codigo_qr', v_bc.codigo_qr,
        'sesion_cover_id', v_bc.sesion_cover_id
      ));
    END LOOP;

    UPDATE public.sesiones_cover
    SET cantidad_vendida = cantidad_vendida + v_cantidad, fecha_actualizacion = v_now
    WHERE id = v_sesion_id;
  END LOOP;

  RETURN jsonb_build_object(
    'compra_cover_id', v_compra_id,
    'numero_transaccion', v_numero,
    'boletas_cover', v_boletas
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.confirmar_compra_cover(p_compra_cover_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now TIMESTAMPTZ := now();
BEGIN
  UPDATE public.compras_cover
  SET
    estado_pago = 'completado',
    estado_compra = 'confirmada',
    fecha_confirmacion = v_now,
    fecha_actualizacion = v_now
  WHERE id = p_compra_cover_id;

  UPDATE public.boletas_cover
  SET estado = 'activa', fecha_actualizacion = v_now
  WHERE compra_cover_id = p_compra_cover_id;

  RETURN jsonb_build_object('ok', true, 'compra_cover_id', p_compra_cover_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.listar_compras_cover_cliente(
  p_cliente_id BIGINT DEFAULT NULL,
  p_limite INT DEFAULT 50
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_limite INT;
BEGIN
  v_uid := coalesce(p_cliente_id, public.fn_usuario_id_actual());
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sesión requerida'; END IF;
  v_limite := least(greatest(coalesce(p_limite, 50), 1), 100);

  RETURN coalesce((
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.fecha_compra DESC)
    FROM (
      SELECT
        c.id, c.numero_transaccion, c.lugar_id, l.nombre AS lugar_nombre,
        c.total, c.estado_pago, c.estado_compra, c.fecha_compra, c.fecha_confirmacion,
        (SELECT count(*)::int FROM public.boletas_cover bc WHERE bc.compra_cover_id = c.id) AS boletas_count
      FROM public.compras_cover c
      JOIN public.lugares l ON l.id = c.lugar_id
      WHERE c.cliente_id = v_uid
      ORDER BY c.fecha_compra DESC
      LIMIT v_limite
    ) t
  ), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.listar_boletas_cover_cliente(
  p_cliente_id BIGINT DEFAULT NULL,
  p_limite INT DEFAULT 200
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_limite INT;
BEGIN
  v_uid := coalesce(p_cliente_id, public.fn_usuario_id_actual());
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sesión requerida'; END IF;
  v_limite := least(greatest(coalesce(p_limite, 200), 1), 500);

  RETURN coalesce((
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.fecha_creacion DESC)
    FROM (
      SELECT
        bc.id,
        bc.compra_cover_id,
        bc.sesion_cover_id,
        bc.tipo_cover_id,
        bc.codigo_qr,
        bc.precio_unitario,
        bc.estado,
        bc.estado_acceso,
        bc.titular_cliente_id,
        bc.fecha_creacion,
        sc.fecha AS sesion_fecha,
        sc.hora_apertura AS sesion_hora_apertura,
        sc.hora_cierre AS sesion_hora_cierre,
        sc.estado AS sesion_estado,
        tc.nombre AS tipo_cover_nombre,
        tc.permite_reingreso,
        c.lugar_id,
        l.nombre AS lugar_nombre,
        c.cliente_id AS compra_cliente_id,
        c.numero_transaccion AS compra_numero_transaccion,
        c.estado_pago AS compra_estado_pago,
        c.estado_compra AS compra_estado_compra,
        c.fecha_compra AS compra_fecha_compra
      FROM public.boletas_cover bc
      JOIN public.compras_cover c ON c.id = bc.compra_cover_id
      JOIN public.lugares l ON l.id = c.lugar_id
      LEFT JOIN public.sesiones_cover sc ON sc.id = bc.sesion_cover_id
      LEFT JOIN public.tipos_cover tc ON tc.id = bc.tipo_cover_id
      WHERE coalesce(bc.titular_cliente_id, c.cliente_id) = v_uid
        AND lower(coalesce(bc.estado, '')) IS DISTINCT FROM 'cancelada'
        AND c.estado_pago = 'completado'
      ORDER BY bc.fecha_creacion DESC
      LIMIT v_limite
    ) t
  ), '[]'::jsonb);
END;
$$;

-- ─── RPC: puerta — entrada / salida con aforo atómico ───────────────────────

CREATE OR REPLACE FUNCTION public.registrar_acceso_cover(
  p_codigo_qr TEXT,
  p_tipo_movimiento TEXT,
  p_sesion_cover_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lector_id BIGINT;
  v_bc public.boletas_cover%ROWTYPE;
  v_compra_cover public.compras_cover%ROWTYPE;
  v_sesion public.sesiones_cover%ROWTYPE;
  v_tipo public.tipos_cover%ROWTYPE;
  v_personas_despues INT;
  v_now TIMESTAMPTZ := now();
BEGIN
  v_lector_id := public.fn_usuario_id_actual();
  IF v_lector_id IS NULL THEN RAISE EXCEPTION 'Sesión requerida'; END IF;
  IF p_tipo_movimiento NOT IN ('entrada', 'salida') THEN RAISE EXCEPTION 'Movimiento inválido'; END IF;
  IF nullif(trim(p_codigo_qr), '') IS NULL THEN RAISE EXCEPTION 'codigo_qr requerido'; END IF;

  SELECT * INTO v_bc FROM public.boletas_cover WHERE codigo_qr = trim(p_codigo_qr);
  IF NOT FOUND THEN
    RAISE EXCEPTION 'QR cover no encontrado';
  END IF;

  SELECT * INTO v_compra_cover FROM public.compras_cover WHERE id = v_bc.compra_cover_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Compra cover no encontrada';
  END IF;
  IF v_compra_cover.estado_pago IS DISTINCT FROM 'completado'
     OR v_compra_cover.estado_compra IS DISTINCT FROM 'confirmada' THEN
    RAISE EXCEPTION 'Compra cover no confirmada';
  END IF;

  SELECT * INTO v_sesion FROM public.sesiones_cover WHERE id = coalesce(p_sesion_cover_id, v_bc.sesion_cover_id) FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Sesión no encontrada'; END IF;
  IF v_sesion.id IS DISTINCT FROM v_bc.sesion_cover_id AND p_sesion_cover_id IS NOT NULL THEN
    RAISE EXCEPTION 'QR no válido para esta sesión';
  END IF;

  SELECT * INTO v_tipo FROM public.tipos_cover WHERE id = v_bc.tipo_cover_id;

  IF p_tipo_movimiento = 'entrada' THEN
    IF v_bc.estado_acceso = 'consumida' AND NOT coalesce(v_tipo.permite_reingreso, true) THEN
      RAISE EXCEPTION 'Entrada ya consumida';
    END IF;
    IF v_sesion.personas_dentro >= v_sesion.aforo_maximo THEN
      RAISE EXCEPTION 'Aforo completo';
    END IF;
    UPDATE public.sesiones_cover
    SET personas_dentro = personas_dentro + 1, fecha_actualizacion = v_now
    WHERE id = v_sesion.id
    RETURNING personas_dentro INTO v_personas_despues;
    UPDATE public.boletas_cover
    SET estado_acceso = 'dentro', entradas_count = entradas_count + 1,
        primera_entrada_at = coalesce(primera_entrada_at, v_now),
        ultima_entrada_at = v_now, fecha_actualizacion = v_now
    WHERE id = v_bc.id;
  ELSE
    IF v_bc.estado_acceso IS DISTINCT FROM 'dentro' THEN
      RAISE EXCEPTION 'No hay entrada registrada para registrar salida';
    END IF;
    UPDATE public.sesiones_cover
    SET personas_dentro = greatest(0, personas_dentro - 1), fecha_actualizacion = v_now
    WHERE id = v_sesion.id
    RETURNING personas_dentro INTO v_personas_despues;
    UPDATE public.boletas_cover
    SET estado_acceso = CASE WHEN coalesce(v_tipo.permite_reingreso, true) THEN 'fuera' ELSE 'consumida' END,
        salidas_count = salidas_count + 1, ultima_salida_at = v_now, fecha_actualizacion = v_now
    WHERE id = v_bc.id;
  END IF;

  INSERT INTO public.accesos_cover (
    boleta_cover_id, sesion_cover_id, tipo_movimiento,
    lector_usuario_id, personas_dentro_despues
  ) VALUES (
    v_bc.id, v_sesion.id, p_tipo_movimiento,
    v_lector_id, v_personas_despues
  );

  RETURN jsonb_build_object(
    'ok', true,
    'estado_acceso', (SELECT estado_acceso FROM public.boletas_cover WHERE id = v_bc.id),
    'personas_dentro', v_personas_despues
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.consultar_aforo_sesion_cover(p_sesion_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sesion public.sesiones_cover%ROWTYPE;
BEGIN
  SELECT * INTO v_sesion FROM public.sesiones_cover WHERE id = p_sesion_id;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  RETURN jsonb_build_object(
    'sesion_cover_id', v_sesion.id,
    'lugar_id', v_sesion.lugar_id,
    'fecha', v_sesion.fecha,
    'estado', v_sesion.estado,
    'aforo_maximo', v_sesion.aforo_maximo,
    'personas_dentro', v_sesion.personas_dentro,
    'cupos_disponibles', greatest(0, v_sesion.aforo_maximo - v_sesion.personas_dentro),
    'cantidad_vendida', v_sesion.cantidad_vendida,
    'cantidad_maxima_venta', v_sesion.cantidad_maxima_venta
  );
END;
$$;

-- ─── Traslados cover (misma tabla traslados_boleta) ───────────────────────────

CREATE OR REPLACE FUNCTION public.fn_traslado_cover_activo(p_boleta_cover_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.traslados_boleta t
    WHERE t.boleta_cover_id = p_boleta_cover_id
      AND t.estado IN ('enviado', 'recibido')
  );
$$;

CREATE OR REPLACE FUNCTION public.iniciar_traslado_boleta_cover(
  p_boleta_cover_id BIGINT,
  p_email_destino TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_bc public.boletas_cover%ROWTYPE;
  v_compra public.compras_cover%ROWTYPE;
  v_destino_id BIGINT;
  v_traslado_id BIGINT;
  v_email TEXT;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Sesión requerida');
  END IF;

  v_email := lower(trim(coalesce(p_email_destino, '')));
  IF v_email = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Email requerido');
  END IF;

  SELECT * INTO v_bc FROM public.boletas_cover WHERE id = p_boleta_cover_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Entrada cover no encontrada');
  END IF;

  SELECT * INTO v_compra FROM public.compras_cover WHERE id = v_bc.compra_cover_id;
  IF v_compra.estado_pago IS DISTINCT FROM 'completado' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'El pago de la compra no está confirmado');
  END IF;

  IF coalesce(v_bc.titular_cliente_id, v_compra.cliente_id) IS DISTINCT FROM v_uid THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No eres titular de esta entrada');
  END IF;

  IF v_bc.estado IN ('consumida', 'cancelada') OR v_bc.estado_acceso = 'consumida' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Esta entrada ya no se puede transferir');
  END IF;

  IF public.fn_traslado_cover_activo(v_bc.id) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Ya hay un traslado pendiente para esta entrada');
  END IF;

  SELECT u.id INTO v_destino_id
  FROM public.usuarios u
  WHERE lower(u.email) = v_email AND u.activo = true
  LIMIT 1;

  IF v_destino_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No hay usuario registrado con ese correo');
  END IF;

  IF v_destino_id = v_uid THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No puedes enviarte la entrada a ti mismo');
  END IF;

  IF nullif(trim(coalesce((SELECT documento_identidad FROM public.usuarios WHERE id = v_destino_id), '')), '') IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'El destinatario debe tener documento en Mi perfil');
  END IF;

  INSERT INTO public.traslados_boleta (
    boleta_cover_id, usuario_origen_id, usuario_destino_id, email_destino, estado
  ) VALUES (
    v_bc.id, v_uid, v_destino_id, v_email, 'enviado'
  )
  RETURNING id INTO v_traslado_id;

  RETURN jsonb_build_object('ok', true, 'traslado_id', v_traslado_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.marcar_traslado_boleta_cover_recibido(p_traslado_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_t public.traslados_boleta%ROWTYPE;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  SELECT * INTO v_t FROM public.traslados_boleta WHERE id = p_traslado_id FOR UPDATE;
  IF NOT FOUND OR v_t.boleta_cover_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Traslado no encontrado');
  END IF;
  IF v_t.usuario_destino_id IS DISTINCT FROM v_uid THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No autorizado');
  END IF;
  IF v_t.estado <> 'enviado' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Estado inválido');
  END IF;
  UPDATE public.traslados_boleta
  SET estado = 'recibido', fecha_recibido = now()
  WHERE id = v_t.id;
  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.aceptar_traslado_boleta_cover(p_traslado_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_t public.traslados_boleta%ROWTYPE;
  v_doc TEXT;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Sesión requerida');
  END IF;

  SELECT documento_identidad INTO v_doc FROM public.usuarios WHERE id = v_uid;
  IF nullif(trim(coalesce(v_doc, '')), '') IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Debes registrar tu documento en Mi perfil antes de aceptar');
  END IF;

  SELECT * INTO v_t FROM public.traslados_boleta WHERE id = p_traslado_id FOR UPDATE;
  IF NOT FOUND OR v_t.boleta_cover_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Traslado no encontrado');
  END IF;
  IF v_t.usuario_destino_id IS DISTINCT FROM v_uid THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No autorizado');
  END IF;
  IF v_t.estado NOT IN ('enviado', 'recibido') THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Este traslado ya fue procesado');
  END IF;

  UPDATE public.boletas_cover
  SET titular_cliente_id = v_uid, fecha_actualizacion = now()
  WHERE id = v_t.boleta_cover_id;

  UPDATE public.traslados_boleta
  SET estado = 'aceptado', fecha_aceptacion = now()
  WHERE id = v_t.id;

  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.rechazar_traslado_boleta_cover(p_traslado_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_t public.traslados_boleta%ROWTYPE;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  SELECT * INTO v_t FROM public.traslados_boleta WHERE id = p_traslado_id FOR UPDATE;
  IF NOT FOUND OR v_t.boleta_cover_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Traslado no encontrado');
  END IF;
  IF v_t.usuario_destino_id IS DISTINCT FROM v_uid THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No autorizado');
  END IF;
  IF v_t.estado NOT IN ('enviado', 'recibido') THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Estado inválido');
  END IF;
  UPDATE public.traslados_boleta
  SET estado = 'rechazado', fecha_rechazo = now()
  WHERE id = v_t.id;
  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.cancelar_traslado_boleta_cover(p_traslado_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
  v_t public.traslados_boleta%ROWTYPE;
BEGIN
  v_uid := public.fn_usuario_id_actual();
  SELECT * INTO v_t FROM public.traslados_boleta WHERE id = p_traslado_id FOR UPDATE;
  IF NOT FOUND OR v_t.boleta_cover_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Traslado no encontrado');
  END IF;
  IF v_t.usuario_origen_id IS DISTINCT FROM v_uid THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Solo el remitente puede cancelar');
  END IF;
  IF v_t.estado NOT IN ('enviado', 'recibido') THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Estado inválido');
  END IF;
  UPDATE public.traslados_boleta
  SET estado = 'cancelado', fecha_cancelacion = now()
  WHERE id = v_t.id;
  RETURN jsonb_build_object('ok', true);
END;
$$;

-- ─── Permisos RPC ─────────────────────────────────────────────────────────────

GRANT EXECUTE ON FUNCTION public.listar_lugares_con_covers(INT, INT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.obtener_lugar_cover(BIGINT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consultar_aforo_sesion_cover(BIGINT) TO authenticated;

GRANT EXECUTE ON FUNCTION public.configurar_lugar_cover(BIGINT, BOOLEAN, TEXT, NUMERIC) TO authenticated;
GRANT EXECUTE ON FUNCTION public.obtener_config_cover_lugar(BIGINT) TO authenticated;

GRANT EXECUTE ON FUNCTION public.upsert_tipo_cover(
  BIGINT, BIGINT, TEXT, TEXT, BIGINT, BOOLEAN, INTEGER, INTEGER, BOOLEAN, BIGINT
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.upsert_plantilla_cover(
  BIGINT, BIGINT, SMALLINT, TIME, TIME, INTEGER, INTEGER, INTEGER, BOOLEAN
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.crear_sesion_cover_manual(
  BIGINT, DATE, TIME, TIME, INTEGER, INTEGER, BIGINT, TEXT
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.actualizar_sesion_cover(
  BIGINT, TIME, TIME, INTEGER, INTEGER, BIGINT
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.inicializar_cover_lugar(
  BIGINT, TEXT, BIGINT, SMALLINT, TIME, TIME, TEXT, INTEGER, INTEGER, BOOLEAN, BIGINT, BIGINT, BOOLEAN
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generar_sesiones_cover_desde_plantillas(DATE) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cambiar_estado_sesion_cover(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.crear_compra_cover_desde_pedido(
  BIGINT, BIGINT, JSONB, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, BIGINT, BIGINT, BIGINT, BOOLEAN
) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.confirmar_compra_cover(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.listar_compras_cover_cliente(BIGINT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.listar_boletas_cover_cliente(BIGINT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_acceso_cover(TEXT, TEXT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.iniciar_traslado_boleta_cover(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.marcar_traslado_boleta_cover_recibido(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aceptar_traslado_boleta_cover(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rechazar_traslado_boleta_cover(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancelar_traslado_boleta_cover(BIGINT) TO authenticated;

-- ─── RPC: listar traslados (SECURITY DEFINER; evita RLS vacío en cliente) ───

CREATE OR REPLACE FUNCTION public.listar_traslados_boleta_salientes(
  p_cliente_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
BEGIN
  v_uid := coalesce(p_cliente_id, public.fn_usuario_id_actual());
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sesión requerida'; END IF;

  RETURN coalesce((
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.fecha_creacion DESC)
    FROM (
      SELECT
        tr.id,
        tr.boleta_id,
        tr.boleta_cover_id,
        tr.usuario_origen_id,
        tr.usuario_destino_id,
        tr.email_destino,
        tr.estado,
        tr.fecha_creacion,
        tr.fecha_recibido,
        tr.fecha_aceptacion,
        tr.fecha_rechazo,
        tr.fecha_cancelacion,
        coalesce(tb.evento_id, c.evento_id) AS evento_id,
        cc.lugar_id AS lugar_id
      FROM public.traslados_boleta tr
      LEFT JOIN public.boletas_compradas b ON b.id = tr.boleta_id
      LEFT JOIN public.compras c ON c.id = b.compra_id
      LEFT JOIN public.tipos_boleta tb ON tb.id = b.tipo_boleta_id
      LEFT JOIN public.boletas_cover bc ON bc.id = tr.boleta_cover_id
      LEFT JOIN public.compras_cover cc ON cc.id = bc.compra_cover_id
      WHERE tr.usuario_origen_id = v_uid
        AND tr.estado IN ('enviado', 'recibido')
      ORDER BY tr.fecha_creacion DESC
    ) t
  ), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.listar_traslados_boleta_pendientes_recibir(
  p_cliente_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
BEGIN
  v_uid := coalesce(p_cliente_id, public.fn_usuario_id_actual());
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sesión requerida'; END IF;

  RETURN coalesce((
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.fecha_creacion DESC)
    FROM (
      SELECT
        tr.id,
        tr.boleta_id,
        tr.boleta_cover_id,
        tr.usuario_origen_id,
        tr.usuario_destino_id,
        tr.email_destino,
        tr.estado,
        tr.fecha_creacion,
        tr.fecha_recibido,
        tr.fecha_aceptacion,
        tr.fecha_rechazo,
        tr.fecha_cancelacion,
        coalesce(tb.evento_id, c.evento_id) AS evento_id,
        cc.lugar_id AS lugar_id,
        uo.email AS usuario_origen_email,
        uo.nombre AS usuario_origen_nombre,
        uo.apellido AS usuario_origen_apellido
      FROM public.traslados_boleta tr
      LEFT JOIN public.boletas_compradas b ON b.id = tr.boleta_id
      LEFT JOIN public.compras c ON c.id = b.compra_id
      LEFT JOIN public.tipos_boleta tb ON tb.id = b.tipo_boleta_id
      LEFT JOIN public.boletas_cover bc ON bc.id = tr.boleta_cover_id
      LEFT JOIN public.compras_cover cc ON cc.id = bc.compra_cover_id
      LEFT JOIN public.usuarios uo ON uo.id = tr.usuario_origen_id
      WHERE tr.usuario_destino_id = v_uid
        AND tr.estado IN ('enviado', 'recibido')
      ORDER BY tr.fecha_creacion DESC
    ) t
  ), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.listar_traslados_boleta_trazabilidad(
  p_cliente_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid BIGINT;
BEGIN
  v_uid := coalesce(p_cliente_id, public.fn_usuario_id_actual());
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sesión requerida'; END IF;

  RETURN coalesce((
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.fecha_creacion DESC)
    FROM (
      SELECT
        tr.id,
        tr.boleta_id,
        tr.boleta_cover_id,
        tr.usuario_origen_id,
        tr.usuario_destino_id,
        tr.email_destino,
        tr.estado,
        tr.fecha_creacion,
        tr.fecha_recibido,
        tr.fecha_aceptacion,
        tr.fecha_rechazo,
        tr.fecha_cancelacion,
        coalesce(tb.evento_id, c.evento_id) AS evento_id,
        cc.lugar_id AS lugar_id
      FROM public.traslados_boleta tr
      LEFT JOIN public.boletas_compradas b ON b.id = tr.boleta_id
      LEFT JOIN public.compras c ON c.id = b.compra_id
      LEFT JOIN public.tipos_boleta tb ON tb.id = b.tipo_boleta_id
      LEFT JOIN public.boletas_cover bc ON bc.id = tr.boleta_cover_id
      LEFT JOIN public.compras_cover cc ON cc.id = bc.compra_cover_id
      WHERE tr.usuario_origen_id = v_uid OR tr.usuario_destino_id = v_uid
      ORDER BY tr.fecha_creacion DESC
    ) t
  ), '[]'::jsonb);
END;
$$;

GRANT EXECUTE ON FUNCTION public.listar_traslados_boleta_salientes(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.listar_traslados_boleta_pendientes_recibir(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.listar_traslados_boleta_trazabilidad(BIGINT) TO authenticated;

ALTER TABLE public.traslados_boleta ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS traslados_boleta_select_participante ON public.traslados_boleta;
CREATE POLICY traslados_boleta_select_participante ON public.traslados_boleta
  FOR SELECT TO authenticated
  USING (
    usuario_origen_id = public.fn_usuario_id_actual()
    OR usuario_destino_id = public.fn_usuario_id_actual()
  );

GRANT SELECT ON public.traslados_boleta TO authenticated;
