-- ============================================================
-- 015_covers_limpieza_legacy_dev.sql
-- SOLO DEV / entornos que aplicaron el 014 antiguo (puente evento
-- espejo) y/o 016 antes del 014 unificado.
--
-- NO ejecutar en master/prod fresh (allí solo corre 014 limpio).
--
-- Orden recomendado en dev:
--   1) Este script (015)
--   2) Re-ejecutar 014_modulo_covers.sql completo (idempotente)
-- ============================================================

-- ─── 1. Eliminar funciones obsoletas ─────────────────────────────────────────

DROP FUNCTION IF EXISTS public.sincronizar_checkout_tipo_cover(
  BIGINT, BIGINT, BIGINT, INTEGER
);

DROP FUNCTION IF EXISTS public.vincular_boleta_cover(BIGINT, BIGINT);

-- Firmas antiguas de upsert_tipo_cover (con evento_id / tipo_boleta_id).
DROP FUNCTION IF EXISTS public.upsert_tipo_cover(
  BIGINT, BIGINT, TEXT, TEXT, BIGINT, BOOLEAN, INTEGER, INTEGER, BOOLEAN, BIGINT, BIGINT
);

DROP FUNCTION IF EXISTS public.upsert_tipo_cover(
  BIGINT, BIGINT, TEXT, TEXT, BIGINT, BOOLEAN, INTEGER, INTEGER, BOOLEAN, BIGINT, BIGINT, BIGINT
);

-- ─── 2. Puente tipos_boleta ↔ tipos_cover ────────────────────────────────────

DROP INDEX IF EXISTS public.idx_tipos_boleta_tipo_cover;

ALTER TABLE public.tipos_boleta
  DROP CONSTRAINT IF EXISTS tipos_boleta_tipo_cover_id_fkey;

ALTER TABLE public.tipos_boleta
  DROP COLUMN IF EXISTS tipo_cover_id;

ALTER TABLE public.tipos_boleta
  DROP COLUMN IF EXISTS es_cover;

-- ─── 3. Columnas puente en tipos_cover y sesiones_cover ─────────────────────

ALTER TABLE public.tipos_cover
  DROP COLUMN IF EXISTS evento_id;

ALTER TABLE public.tipos_cover
  DROP COLUMN IF EXISTS tipo_boleta_id;

ALTER TABLE public.sesiones_cover
  DROP COLUMN IF EXISTS evento_id;

ALTER TABLE public.sesiones_cover
  DROP COLUMN IF EXISTS tipo_boleta_id;

-- ─── 4. Marcador en eventos ─────────────────────────────────────────────────

ALTER TABLE public.eventos
  DROP COLUMN IF EXISTS es_cover;

-- ─── 5. Asegurar columnas del checkout independiente (por si faltó 016) ─────

ALTER TABLE public.tipos_cover
  ADD COLUMN IF NOT EXISTS wompi_cuenta_id BIGINT
  REFERENCES public.wompi_cuentas(id) ON DELETE SET NULL;

ALTER TABLE public.transacciones_checkout
  ADD COLUMN IF NOT EXISTS lugar_id BIGINT
  REFERENCES public.lugares(id) ON DELETE SET NULL;

ALTER TABLE public.transacciones_checkout
  ADD COLUMN IF NOT EXISTS compra_cover_id BIGINT;

DO $$
BEGIN
  BEGIN
    ALTER TABLE public.transacciones_checkout
      ALTER COLUMN evento_id DROP NOT NULL;
  EXCEPTION
    WHEN undefined_column THEN NULL;
  END;
END $$;

-- compras_cover (tabla del flujo independiente)
CREATE TABLE IF NOT EXISTS public.compras_cover (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  lugar_id BIGINT NOT NULL REFERENCES public.lugares(id) ON DELETE RESTRICT,
  numero_transaccion TEXT NOT NULL UNIQUE,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  descuento_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  porcentaje_servicio NUMERIC(5,2) NOT NULL DEFAULT 0,
  valor_servicio NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  cupon_id BIGINT REFERENCES public.cupones_descuento(id) ON DELETE SET NULL,
  estado_pago TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado_pago IN ('pendiente', 'completado', 'fallido')),
  estado_compra TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado_compra IN ('pendiente', 'confirmada', 'cancelada')),
  wompi_cuenta_id BIGINT REFERENCES public.wompi_cuentas(id) ON DELETE SET NULL,
  wompi_transaction_id TEXT,
  wompi_reference TEXT,
  wompi_status TEXT,
  metodo_pago TEXT,
  fecha_compra TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_confirmacion TIMESTAMPTZ,
  fecha_cancelacion TIMESTAMPTZ,
  motivo_cancelacion TEXT,
  transaccion_checkout_id BIGINT REFERENCES public.transacciones_checkout(id) ON DELETE SET NULL,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'transacciones_checkout_compra_cover_id_fkey'
  ) THEN
    ALTER TABLE public.transacciones_checkout
      ADD CONSTRAINT transacciones_checkout_compra_cover_id_fkey
      FOREIGN KEY (compra_cover_id) REFERENCES public.compras_cover(id) ON DELETE SET NULL;
  END IF;
END $$;

-- boletas_cover: columnas del flujo independiente
ALTER TABLE public.boletas_cover
  ADD COLUMN IF NOT EXISTS compra_cover_id BIGINT
  REFERENCES public.compras_cover(id) ON DELETE CASCADE;

ALTER TABLE public.boletas_cover
  ADD COLUMN IF NOT EXISTS codigo_qr TEXT;

ALTER TABLE public.boletas_cover
  ADD COLUMN IF NOT EXISTS precio_unitario NUMERIC(12,2) NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'boletas_cover'
      AND column_name = 'estado'
  ) THEN
    ALTER TABLE public.boletas_cover
      ADD COLUMN estado TEXT NOT NULL DEFAULT 'pendiente'
      CHECK (estado IN ('pendiente', 'activa', 'cancelada', 'consumida'));
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_boletas_cover_codigo_qr
  ON public.boletas_cover(codigo_qr)
  WHERE codigo_qr IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_boletas_cover_compra
  ON public.boletas_cover(compra_cover_id)
  WHERE compra_cover_id IS NOT NULL;

-- ─── 6. Quitar puente boletas_compradas en covers ───────────────────────────

-- Covers vinculados solo por boleta_id (sin compra_cover) ya no aplican.
DELETE FROM public.boletas_cover WHERE compra_cover_id IS NULL;

-- La política RLS vieja referencia boleta_id; hay que quitarla antes del DROP COLUMN.
DROP POLICY IF EXISTS boletas_cover_select_titular ON public.boletas_cover;

DROP INDEX IF EXISTS public.idx_boletas_cover_boleta;
DROP INDEX IF EXISTS public.idx_accesos_cover_boleta;

ALTER TABLE public.accesos_cover
  DROP COLUMN IF EXISTS boleta_id;

ALTER TABLE public.boletas_cover
  DROP CONSTRAINT IF EXISTS boletas_cover_boleta_id_key;

ALTER TABLE public.boletas_cover
  DROP CONSTRAINT IF EXISTS boletas_cover_boleta_id_fkey;

ALTER TABLE public.boletas_cover
  DROP COLUMN IF EXISTS boleta_id;

DROP POLICY IF EXISTS boletas_cover_select_titular ON public.boletas_cover;
CREATE POLICY boletas_cover_select_titular ON public.boletas_cover
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.compras_cover cc
      WHERE cc.id = boletas_cover.compra_cover_id
        AND cc.cliente_id = public.fn_usuario_id_actual()
    )
  );

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'boletas_cover'
      AND column_name = 'compra_cover_id'
      AND is_nullable = 'YES'
  ) THEN
    ALTER TABLE public.boletas_cover
      ALTER COLUMN compra_cover_id SET NOT NULL;
  END IF;
EXCEPTION
  WHEN others THEN
    RAISE NOTICE 'compra_cover_id sigue nullable: revisa filas huérfanas en boletas_cover';
END $$;

CREATE INDEX IF NOT EXISTS idx_accesos_cover_boleta_cover
  ON public.accesos_cover(boleta_cover_id, fecha_creacion DESC);

-- ─── 7. Nota post-ejecución ───────────────────────────────────────────────────
-- Ejecuta ahora en el SQL Editor de Supabase:
--   supabase/migrations/014_modulo_covers.sql
-- Eso recrea RPCs (upsert_tipo_cover, obtener_lugar_cover, inicializar_cover_lugar,
-- crear_compra_cover_desde_pedido, registrar_acceso_cover, etc.) sin referencias legacy.
--
-- Eventos espejo creados por sincronizar_checkout_tipo_cover quedan en `eventos`
-- pero ya no se usan; puedes archivarlos/desactivarlos manualmente si lo deseas.
